# Generated by Django 5.2.8 on 2025-12-15 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('built', 'Built'), ('pruned', 'Pruned'), ('parsed', 'Parsed'), ('indexed', 'Indexed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('merged_schedules', models.JSONField(blank=True, null=True)),
                ('must_be_indexed_after_scheduling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='must_be_indexed_before_schedulings', to='scheduling.scheduling')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='home.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PruningParsing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pruning_history_id', models.PositiveIntegerField()),
                ('parsing_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruning_parsings', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'pruning_history_id', 'parsing_history_id')},
            },
        ),
        migrations.CreateModel(
            name='ImagePruning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_history_id', models.PositiveIntegerField()),
                ('pruning_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_prunings', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'image_history_id', 'pruning_history_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalChurch',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_churches', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'church_history_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_images', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'image_history_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalOClocherMatching',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oclocher_matching_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_oclocher_matchings', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'oclocher_matching_history_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalOClocherSchedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oclocher_schedule_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_oclocher_schedules', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'oclocher_schedule_history_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalScraping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_scrapings', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'scraping_history_id')},
            },
        ),
        migrations.CreateModel(
            name='ScrapingPruning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_history_id', models.PositiveIntegerField()),
                ('pruning_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_prunings', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'scraping_history_id', 'pruning_history_id')},
            },
        ),
    ]
