# Generated by Django 5.2.9 on 2025-12-30 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_historicalscraping'),
        ('scheduling', '0002_alter_scheduling_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('indexed_end_time', models.TimeField(db_index=True)),
                ('displayed_end_time', models.TimeField(null=True)),
                ('is_explicitely_other', models.BooleanField(null=True)),
                ('has_been_moderated', models.BooleanField()),
                ('church_color', models.CharField(max_length=9)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_events', to='home.church')),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_events', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('church', 'day', 'start_time', 'displayed_end_time', 'is_explicitely_other')},
            },
        ),
    ]
