# Generated by Django 5.2.9 on 2025-12-30 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_indexevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('built', 'Built'), ('pruned', 'Pruned'), ('parsed', 'Parsed'), ('matched', 'Matched'), ('indexed', 'Indexed'), ('cancelled', 'Cancelled')], max_length=16),
        ),
        migrations.CreateModel(
            name='SchedulingHistoricalOClocherLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oclocher_location_history_id', models.PositiveIntegerField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_oclocher_locations', to='scheduling.scheduling')),
            ],
            options={
                'unique_together': {('scheduling', 'oclocher_location_history_id')},
            },
        ),
    ]
