# Generated by Django 5.2.9 on 2026-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_scheduling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='must_be_indexed_after_scheduling',
        ),
    ]
