# Generated by Django 5.2.9 on 2026-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_scheduling_must_be_indexed_after_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('built', 'Built'), ('pruned', 'Pruned'), ('parsed', 'Parsed'), ('matched', 'Matched'), ('indexed', 'Indexed')], max_length=16),
        ),
    ]
