# Generated by Django 5.2.9 on 2026-01-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_historicalparsingmoderation_parsingmoderation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalparsingmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parsingmoderation',
            table=None,
        ),
    ]
