# Generated by Django 5.2.9 on 2026-01-20 20:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_historicalparsingmoderation_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='HistoricalParsing',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('truncated_html', models.TextField(editable=False)),
                ('truncated_html_hash', models.CharField(editable=False, max_length=32)),
                ('church_desc_by_id', models.JSONField(editable=False)),
                ('llm_json', models.JSONField(blank=True, null=True)),
                ('llm_json_version', models.CharField(default='v1.0', max_length=6)),
                ('llm_provider', models.CharField(choices=[('openai', 'OPENAI')])),
                ('llm_model', models.CharField(max_length=100)),
                ('prompt_template_hash', models.CharField(max_length=32)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_json', models.JSONField(blank=True, null=True)),
                ('human_json_version', models.CharField(default='v1.0', max_length=6)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical parsing',
                'verbose_name_plural': 'historical parsings',
                'db_table': 'home_historicalparsing',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='Parsing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truncated_html', models.TextField(editable=False)),
                ('truncated_html_hash', models.CharField(editable=False, max_length=32)),
                ('church_desc_by_id', models.JSONField(editable=False)),
                ('llm_json', models.JSONField(blank=True, null=True)),
                ('llm_json_version', models.CharField(default='v1.0', max_length=6)),
                ('llm_provider', models.CharField(choices=[('openai', 'OPENAI')])),
                ('llm_model', models.CharField(max_length=100)),
                ('prompt_template_hash', models.CharField(max_length=32)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_json', models.JSONField(blank=True, null=True)),
                ('human_json_version', models.CharField(default='v1.0', max_length=6)),
            ],
            options={
                'db_table': 'home_parsing',
                'unique_together': {('truncated_html_hash', 'church_desc_by_id')},
            },
        )]),
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='parsing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling.parsing'),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='parsing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='scheduling.parsing'),
        ),
    ]
