# Generated by Django 5.2.9 on 2026-01-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_historicalparsing_parsing_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalparsing',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parsing',
            table=None,
        ),
    ]
