# Generated by Django 5.2.9 on 2026-01-20 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_historicalparsing_table_alter_parsing_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='FineTunedLLM',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('fine_tuning', 'Fine Tuning'), ('failed', 'Failed'), ('draft', 'Draft'), ('prod', 'Prod')], max_length=12)),
                ('dataset_name', models.CharField(max_length=100)),
                ('base_model', models.CharField(max_length=100)),
                ('fine_tune_job_id', models.CharField(max_length=100)),
                ('fine_tuned_model', models.CharField(max_length=100, null=True)),
                ('error_detail', models.TextField(null=True)),
                ('parsing_moderations', models.ManyToManyField(related_name='fine_tuned_llms', to='scheduling.parsingmoderation')),
            ],
            options={
                'db_table': 'home_finetunedllm',
            },
        )]),
    ]
