# Generated by Django 5.2.9 on 2026-01-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_finetunedllm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finetunedllm',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelTable(
            name='finetunedllm',
            table=None,
        ),
    ]
