# Generated by Django 5.2.9 on 2026-01-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_alter_finetunedllm_options_alter_finetunedllm_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulinghistoricaloclochermatching',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='schedulinghistoricaloclochermatching',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schedulinghistoricaloclochermatching',
            name='scheduling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historical_oclocher_matching', to='scheduling.scheduling'),
        ),
    ]
