# Generated by Django 5.2.9 on 2026-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_classifier_pruning_historicalclassifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifier',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='pruning',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelTable(
            name='classifier',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalclassifier',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalpruning',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalpruningmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalsentence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalsentencemoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pruning',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pruningmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentencemoderation',
            table=None,
        ),
    ]
