# Generated by Django 5.2.9 on 2026-01-30 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_classifier_options_alter_pruning_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('pruning', 'Pruning'), ('parsing', 'Parsing')], max_length=8)),
                ('status', models.CharField(choices=[('done', 'Done'), ('failure', 'Failure')], max_length=8)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_logs', to='home.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
