# Generated by Django 5.2.9 on 2026-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        ('scheduling', '0016_log'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='indexevent',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_events', to='registry.church'),
        ),
        migrations.AlterField(
            model_name='log',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_logs', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsing_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pruning_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence_moderations', to='registry.diocese'),
        ),
    ])]
