# Generated by Django 5.2.9 on 2026-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_alter_historicalparsingmoderation_diocese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
