# Generated by Django 5.2.11 on 2026-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_historicalschedulingmoderation_schedulingmoderation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='merged_schedules',
            new_name='church_uuid_by_id',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='sourced_schedules_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
