# Generated by Django 5.2.11 on 2026-02-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_rename_merged_schedules_scheduling_church_uuid_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='resources_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
