# Generated by Django 5.2.11 on 2026-02-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_historicalwebsitemoderation_conflict_church_and_more'),
        ('scheduling', '0021_scheduling_resources_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexevent',
            unique_together={('church', 'day', 'start_time', 'displayed_end_time')},
        ),
        migrations.RemoveField(
            model_name='indexevent',
            name='is_explicitely_other',
        ),
    ]
