# Generated by Django 5.2.12 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
        ('scheduling', '0022_alter_indexevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_moderations', to='registry.diocese'),
        ),
    ]
