# Generated by Django 5.2.12 on 2026-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0024_historicalwebsiteschedulesmoderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexevent',
            name='indexed_end_tz_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='indexevent',
            name='start_tz_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
