# Generated by Django 5.2.12 on 2026-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0025_indexevent_indexed_end_tz_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexevent',
            name='indexed_end_tz_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='indexevent',
            name='start_tz_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
