# Generated by Django 5.2.12 on 2026-03-27 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
        ('scheduling', '0026_alter_indexevent_indexed_end_tz_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteSchedules',
            new_name='ValidatedSchedules',
        ),
    ]
