# Generated by Django 5.2.12 on 2026-03-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
        ('scheduling', '0027_rename_websiteschedules_validatedschedules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedschedules',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validatedschedules',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validated_schedules', to='registry.website'),
        ),
    ]
