# Generated by Django 5.2.12 on 2026-03-27 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
        ('scheduling', '0028_alter_validatedschedules_validated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalWebsiteSchedulesModeration',
            new_name='HistoricalValidatedSchedulesModeration',
        ),
        migrations.RenameModel(
            old_name='WebsiteSchedulesModeration',
            new_name='ValidatedSchedulesModeration',
        ),
        migrations.AlterModelOptions(
            name='historicalvalidatedschedulesmoderation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical validated schedules moderation', 'verbose_name_plural': 'historical validated schedules moderations'},
        ),
    ]
