# Generated by Django 5.2.12 on 2026-03-27 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
        ('scheduling', '0029_rename_historicalwebsiteschedulesmoderation_historicalvalidatedschedulesmoderation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_schedules_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='marked_as_bug_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_schedules_marked_as_bug_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_schedules_moderation_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validated_schedules_moderation', to='registry.website'),
        ),
    ]
