# Generated by Django 5.2.12 on 2026-03-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_alter_validatedschedulesmoderation_diocese_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_schedules_validated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
