# Generated by Django 5.2.12 on 2026-03-30 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_alter_validatedschedulesmoderation_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexevent',
            name='schedules_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=None),
        ),
    ]
