# Generated by Django 5.2.12 on 2026-03-31 11:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0032_indexevent_schedules_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexevent',
            name='schedules_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None),
        ),
    ]
