# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0033_alter_indexevent_schedules_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalpruningmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalschedulingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentencemoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalidatedschedulesmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='parsingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pruningmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schedulingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sentencemoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='validatedschedulesmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
