# Generated by Django 5.2.13 on 2026-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0034_historicalparsingmoderation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalpruningmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalschedulingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalsentencemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalvalidatedschedulesmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='parsingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='pruningmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='schedulingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='sentencemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='validatedschedulesmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
    ]
