# Generated by Django 5.2.13 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_remove_historicalparsingmoderation_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalschedulingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalvalidatedschedulesmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='schedulingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='validatedschedulesmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
    ]
