# Generated by Django 5.2.13 on 2026-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0037_alter_historicalparsingmoderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedulingmoderation',
            name='category',
            field=models.CharField(choices=[('no_source', 'No Source'), ('no_schedule', 'No Schedule'), ('desc_conflict', 'Desc Conflict'), ('unknown_place', 'Unknown Place'), ('sched_conflict', 'Schedules Conflict'), ('ok', 'Ok')], max_length=16),
        ),
        migrations.AlterField(
            model_name='schedulingmoderation',
            name='category',
            field=models.CharField(choices=[('no_source', 'No Source'), ('no_schedule', 'No Schedule'), ('desc_conflict', 'Desc Conflict'), ('unknown_place', 'Unknown Place'), ('sched_conflict', 'Schedules Conflict'), ('ok', 'Ok')], max_length=16),
        ),
    ]
