# Generated by Django 5.2.9 on 2026-01-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchtrouverunemesse',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='diocese',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.RenameIndex(
            model_name='church',
            new_name='registry_ch_locatio_a98348_gist',
            old_name='home_church_locatio_11d715_gist',
        ),
        migrations.AlterModelTable(
            name='church',
            table=None,
        ),
        migrations.AlterModelTable(
            name='churchllmname',
            table=None,
        ),
        migrations.AlterModelTable(
            name='churchmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='churchtrouverunemesse',
            table=None,
        ),
        migrations.AlterModelTable(
            name='churchtrouverunemessellmname',
            table=None,
        ),
        migrations.AlterModelTable(
            name='diocese',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalchurch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalchurchmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicaldiocese',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalparish',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalparishmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalwebsite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalwebsitemoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parish',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parishmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='website',
            table=None,
        ),
        migrations.AlterModelTable(
            name='websitemoderation',
            table=None,
        ),
    ]
