# Generated by Django 5.2.9 on 2026-02-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_churchtrouverunemesse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('hu_diocese', 'Home Url Diocese'), ('google_search', 'Google Search')], max_length=32),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('hu_diocese', 'Home Url Diocese'), ('google_search', 'Google Search')], max_length=32),
        ),
    ]
