# Generated by Django 5.2.11 on 2026-02-09 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_historicalwebsitemoderation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsite',
            name='contact_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
