# Generated by Django 5.2.11 on 2026-02-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_historicalwebsite_contact_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebsitemoderation',
            name='conflict_church',
        ),
        migrations.RemoveField(
            model_name='historicalwebsitemoderation',
            name='conflict_day',
        ),
        migrations.RemoveField(
            model_name='websitemoderation',
            name='conflict_church',
        ),
        migrations.RemoveField(
            model_name='websitemoderation',
            name='conflict_day',
        ),
    ]
