# Generated by Django 5.2.11 on 2026-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_historicalwebsitemoderation_conflict_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='oclocher_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='oclocher_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
