# Generated by Django 5.2.12 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_church_oclocher_id_historicalchurch_oclocher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_moderations', to='registry.diocese'),
        ),
    ]
