# Generated by Django 5.2.12 on 2026-04-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='crawling',
        ),
        migrations.RemoveField(
            model_name='website',
            name='crawling',
        ),
    ]
