# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_remove_historicalwebsite_crawling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurchmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalparishmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebsitemoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='websitemoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
