# Generated by Django 5.2.13 on 2026-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_churchmoderation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalchurchmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalparishmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalwebsitemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='websitemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
    ]
