# Generated by Django 5.2.13 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_remove_churchmoderation_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalchurchmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalparishmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
    ]
