##
# Set up and configure postgres
# Inspired by :
# - https://stormatics.tech/blogs/install-postgresql-using-ansible-on-remote-servers
# - https://gist.github.com/kharandziuk/d11aab8b1560d408032911140a0b103a

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: true

- name: Modify listen_addresses in postgresql.conf to accept remote connection
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: "^#?listen_addresses = '.*'"
    line: "listen_addresses = '*'"
    state: present
  become: true
  notify:
    - restart postgres

- name: Configure a new postgresql user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become_user: postgres
  become: true
  notify:
    - restart postgres

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become_user: postgres
  become: true

- name: install postgis extension
  postgresql_ext:
    name: postgis
    db: "{{ db_name }}"
  become: true
  become_user: postgres

- name: copy pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/15/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  become: true
  notify:
    - restart postgres
