##
# Set up and configure postgres
# Inspired by :
# - https://stormatics.tech/blogs/install-postgresql-using-ansible-on-remote-servers
# - https://gist.github.com/kharandziuk/d11aab8b1560d408032911140a0b103a

- name: Add the PostgreSQL GPG key as a keyring
  ansible.builtin.shell: |
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-pgdg.gpg
  args:
    creates: /usr/share/keyrings/postgresql-pgdg.gpg
  become: true

- name: Add the PostgreSQL PPA
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/postgresql-pgdg.gpg] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install required packages
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - postgresql-15-postgis-3
      - postgresql-15-pgvector
    state: latest
  become: true

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: true

- name: Modify listen_addresses in postgresql.conf to accept remote connection
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: "^#?listen_addresses = '.*'"
    line: "listen_addresses = '*'"
    state: present
  become: true
  notify:
    - restart postgres

- name: Configure a new postgresql user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become_user: postgres
  become: true
  notify:
    - restart postgres

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become_user: postgres
  become: true

- name: install postgis extension
  postgresql_ext:
    name: postgis
    db: "{{ db_name }}"
  become: true
  become_user: postgres

- name: install pgvector extension
  postgresql_ext:
    name: vector
    db: "{{ db_name }}"
  become: true
  become_user: postgres

- name: copy pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/15/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  become: true
  notify:
    - restart postgres
