##
# Install OpenTelemetry Collector
##

- name: Install OpenTelemetry Collector
  ansible.builtin.include_role:
    name: grafana.grafana.opentelemetry_collector
  vars:
    otel_collector_version: 0.114.0
    otel_collector_receivers:
      otlp:
        protocols:
          http:
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
              system.cpu.time:
                enabled: false
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
              system.memory.usage:
                enabled: false
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
              system.filesystem.usage:
                enabled: false
              system.filesystem.inodes.usage:
                enabled: false

    otel_collector_processors:
      resourcedetection:
        detectors: [env, system]
        timeout: 2s
        system:
          hostname_sources: [os]
      filter/ottl:
        error_mode: ignore
        metrics:
          datapoint:
            - 'metric.name == "system.filesystem.utilization" and attributes["mountpoint"] != "/"'
      batch: {}
      attributes/betterstack:
        actions:
          - key: better_stack_source_token
            value: '{{ otel_better_stack_source_token }}'
            action: insert

    otel_collector_exporters:
#      debug:
#        verbosity: detailed
      prometheusremotewrite/betterstack:
        endpoint: "https://in-otel.logs.betterstack.com/metrics"

    otel_collector_service:
      pipelines:
        metrics:
          receivers: [hostmetrics, otlp]
          processors: [resourcedetection, filter/ottl, batch, attributes/betterstack]
          exporters: [prometheusremotewrite/betterstack]
