##
# Install OpenTelemetry Collector with AWS CloudWatch Exporter
##

- name: Ensure snap is installed
  apt:
    name: snapd
    state: present
    update_cache: yes
  become: true

- name: Ensure snapd service is running
  service:
    name: snapd
    state: started
    enabled: yes
  become: true

- name: Install AWS CLI using snap
  snap:
    name: aws-cli
    state: present
    classic: true
  become: true

- name: Ensure the /home/otel directory exists
  file:
    path: /home/otel
    state: directory
    owner: otel
    group: otel
    mode: '0755'
  become: true

- name: Create AWS credentials directory
  file:
    path: "/home/otel/.aws"
    state: directory
    owner: otel
    group: otel
    mode: "0700"
  become_user: "otel"
  become: true

- name: Configure AWS credentials
  copy:
    dest: "/home/otel/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ otel_aws_access_key_id }}
      aws_secret_access_key = {{ otel_aws_secret_access_key }}
      region = eu-west-3
    owner: otel
    group: otel
    mode: "0600"
  become_user: "otel"
  become: true

- name: Configure AWS config
  copy:
    dest: "/home/otel/.aws/config"
    content: |
      [default]
      region = eu-west-3
      output = json
    owner: otel
    group: otel
    mode: "0600"
  become_user: "otel"
  become: true

- name: Install OpenTelemetry Collector
  ansible.builtin.include_role:
    name: grafana.grafana.opentelemetry_collector
  vars:
    otel_collector_receivers:
      hostmetrics:
        collection_interval: 60s
        scrapers:
          cpu: {}              # CPU usage metrics
          memory: {}           # RAM usage metrics

    otel_collector_processors:
      batch: {}                # Batch processor for metrics
      resourcedetection:
        detectors: [env, system]
        timeout: 2s
        system:
          hostname_sources: [os]

    otel_collector_exporters:
      awsemf: # AWS CloudWatch Embedded Metric Format exporter
        region: eu-west-3
        log_group_name: /metrics/opentelemetry
        log_stream_name: 'confessio-stream'
        namespace: 'confessio'
        log_retention: 60
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: "NoDimensionRollup"

    otel_collector_service:
      pipelines:
        metrics:
          receivers: [hostmetrics]
          processors: [resourcedetection, batch]
          exporters: [awsemf]
