##
# Run db migrations and get all static files
##
- name: Make www-data as owner of static files directory
  file:
    dest: "{{ static_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    mode: "777"
  become: true

- name: Migrate database, populate history, and collect static files
  shell: |
    . {{ app_dir }}/.env && \
    {{ venv_python }} {{ app_dir }}/manage.py migrate && \
    {{ venv_python }} {{ app_dir }}/manage.py populate_history --auto && \
    {{ venv_python }} {{ app_dir }}/manage.py collectstatic --noinput
