##
# Install crons commands
##
- name: Add cron for crawling parishes
  cron:
    name: daily_crawl_parishes
    special_time: daily
    job: "(tmux has-session -t crawl_parishes || tmux new-session -d -s crawl_parishes) && tmux send-keys -t crawl_parishes '. {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py crawl_parishes' C-m"

- name: Add cron for scraping pages
  cron:
    name: hourly_scrape_parishes
    special_time: hourly
    job: "(tmux has-session -t scrape_parishes || tmux new-session -d -s scrape_parishes) && tmux send-keys -t scrape_parishes '. {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py scrape_parishes' C-m"
