# Generated by Django 5.2.9 on 2026-01-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='searchhit',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelTable(
            name='historicalreportmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reportmoderation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='searchhit',
            table=None,
        ),
    ]
