# Generated by Django 5.2.9 on 2026-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_report_options_alter_searchhit_options_and_more'),
        ('registry', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='historicalreportmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='report',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='reportmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_moderations', to='registry.diocese'),
        ),
    ])]
