# Generated by Django 5.2.12 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_historicalreportmoderation_diocese_and_more'),
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_moderations', to='registry.diocese'),
        ),
    ]
