# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_reportmoderation_diocese'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reportmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
