# Generated by Django 5.2.12 on 2026-04-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_historicalreportmoderation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='error_type',
            field=models.CharField(blank=True, choices=[('outdated', 'Outdated'), ('churches', 'Churches'), ('paragraphs', 'Paragraphs'), ('schedules', 'Schedules')], max_length=10, null=True),
        ),
    ]
