# Generated by Django 5.2.13 on 2026-04-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_report_error_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportmoderation',
            name='category',
            field=models.CharField(choices=[('good', 'Good'), ('error', 'Error'), ('comment', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback_type',
            field=models.CharField(choices=[('good', 'Good'), ('error', 'Error'), ('comment', 'Comment')], max_length=8),
        ),
        migrations.AlterField(
            model_name='reportmoderation',
            name='category',
            field=models.CharField(choices=[('good', 'Good'), ('error', 'Error'), ('comment', 'Comment')], max_length=16),
        ),
    ]
