# Generated by Django 5.2.13 on 2026-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_historicalreportmoderation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreportmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='historicalreportmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='historicalreportmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='historicalreportmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='historicalreportmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='reportmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='reportmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='reportmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='reportmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='reportmoderation',
            name='validated_by',
        ),
    ]
