# Generated by Django 5.2.13 on 2026-04-15 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_alter_historicalreportmoderation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteHit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('rank', models.PositiveSmallIntegerField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('item_type', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_context', models.CharField(max_length=255)),
                ('item_latitude', models.FloatField(null=True)),
                ('item_longitude', models.FloatField(null=True)),
                ('item_uuid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
