# Generated by Django 5.2.9 on 2026-01-30 17:19

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0120_alter_scraping_prunings_delete_classifier_and_more'),
        ('scheduling', '0015_alter_classifier_options_alter_pruning_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_detail', models.TextField(null=True)),
                ('nb_visited_links', models.PositiveSmallIntegerField()),
                ('nb_success_links', models.PositiveSmallIntegerField()),
                ('recrawl_triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'home_crawling',
            },
        ),
        migrations.CreateModel(
            name='HistoricalScraping',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('url', models.URLField(max_length=300)),
                ('nb_iterations', models.PositiveSmallIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
            ],
            options={
                'verbose_name': 'historical scraping',
                'verbose_name_plural': 'historical scrapings',
                'db_table': 'home_historicalscraping',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=300)),
                ('nb_iterations', models.PositiveSmallIntegerField()),
                ('prunings', models.ManyToManyField(related_name='scrapings', to='scheduling.pruning')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='home.website')),
            ],
            options={
                'db_table': 'home_scraping',
                'unique_together': {('url', 'website')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteForbiddenPath',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=300)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_paths', to='home.website')),
            ],
            options={
                'db_table': 'home_websiteforbiddenpath',
                'unique_together': {('website', 'path')},
            },
        ),
    ])]
