# Generated by Django 5.2.9 on 2026-01-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawling',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelTable(
            name='crawling',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalscraping',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scraping',
            table=None,
        ),
        migrations.AlterModelTable(
            name='websiteforbiddenpath',
            table=None,
        ),
    ]
