# Generated by Django 5.2.9 on 2026-01-31 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_log'),
        ('registry', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='historicalscraping',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='log',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawling_logs', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='websiteforbiddenpath',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_paths', to='registry.website'),
        ),
    ])]
