# Generated by Django 5.2.11 on 2026-02-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_crawlingmoderation_historicalcrawlingmoderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscraping',
            name='nb_iterations',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='nb_iterations',
        ),
    ]
