# Generated by Django 5.2.12 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_remove_historicalscraping_nb_iterations_and_more'),
        ('registry', '0007_alter_churchmoderation_diocese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawling_moderations', to='registry.diocese'),
        ),
    ]
