# Generated by Django 5.2.12 on 2026-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_alter_crawlingmoderation_diocese'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='nb_success_links',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='nb_visited_links',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
