# Generated by Django 5.2.12 on 2026-04-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0009_log_error_detail_log_nb_success_links_and_more'),
        ('registry', '0008_remove_historicalwebsite_crawling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawling',
        ),
    ]
