# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0010_delete_crawling'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrawlingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
