# Generated by Django 5.2.13 on 2026-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0011_crawlingmoderation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalcrawlingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], default='to_validate', max_length=12),
        ),
    ]
