# Generated by Django 5.2.13 on 2026-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0012_crawlingmoderation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='crawlingmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='crawlingmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='crawlingmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='crawlingmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='historicalcrawlingmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='historicalcrawlingmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='historicalcrawlingmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='historicalcrawlingmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcrawlingmoderation',
            name='validated_by',
        ),
    ]
