# Generated by Django 5.2.13 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0013_remove_crawlingmoderation_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalcrawlingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
    ]
