# Generated by Django 5.0.9 on 2024-11-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_fresh_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsing',
            name='websites',
        ),
    ]
