# Generated by Django 5.0.9 on 2024-12-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_parsing_websites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_scraping', to='home.page'),
        ),
    ]
