# Generated by Django 4.2 on 2023-04-19 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_church_parish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='home.parish'),
        ),
        migrations.CreateModel(
            name='Scrapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confession_html', models.TextField()),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrappings', to='home.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
