# Generated by Django 4.2 on 2023-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_church_parish_scrapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapping',
            name='nb_iterations',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
