# Generated by Django 5.0.9 on 2024-12-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_page_scraping_temp_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraping',
            name='temp_page',
        ),
    ]
