# Generated by Django 4.2 on 2023-04-21 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_scrapping_nb_iterations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confession_html', models.TextField()),
                ('nb_iterations', models.PositiveSmallIntegerField()),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='home.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Scrapping',
        ),
    ]
