# Generated by Django 4.2 on 2023-05-07 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_scraping_delete_scrapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='scraping',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.parish')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
