# Generated by Django 5.0.9 on 2024-12-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_scraping_temp_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawling',
            old_name='website',
            new_name='website_temp',
        ),
    ]
