# Generated by Django 4.2 on 2023-05-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_church_options_alter_parish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='confession_hours_url',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='parish',
        ),
        migrations.AddField(
            model_name='scraping',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='home.page'),
            preserve_default=False,
        ),
    ]
