# Generated by Django 5.0.9 on 2024-12-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_historicalwebsite_crawling_website_crawling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawling',
            name='website_temp',
        ),
    ]
