# Generated by Django 4.2 on 2023-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_parish_confession_hours_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='confession_html',
            field=models.TextField(null=True),
        ),
    ]
