# Generated by Django 4.2 on 2023-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_scraping_confession_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='messesinfo_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='messesinfo_community_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='messesinfo_network_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
