# Generated by Django 5.0.10 on 2024-12-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_historicalwebsite_unreliability_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='human_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='llm_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='human_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='llm_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='crawling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website', to='home.crawling'),
        ),
    ]
