# Generated by Django 4.2 on 2023-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_church_messesinfo_id_parish_messesinfo_community_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='home_url',
            field=models.URLField(null=True),
        ),
    ]
