# Generated by Django 4.2 on 2023-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_church_messesinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='home_url',
            field=models.URLField(),
        ),
    ]
