# Generated by Django 4.2 on 2023-05-26 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_parish_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
