# Generated by Django 5.0.10 on 2024-12-11 18:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_historicalparsingmoderation_validated_schedules_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpruning',
            name='human_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalpruning',
            name='ml_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='pruning',
            name='human_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='pruning',
            name='ml_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
    ]
