# Generated by Django 4.2 on 2023-06-06 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_church_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField()),
                ('error_detail', models.TextField(null=True)),
                ('nb_crawled_pages', models.PositiveSmallIntegerField()),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawlings', to='home.parish')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
