# Generated by Django 4.2 on 2023-06-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_crawling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawling',
            old_name='nb_crawled_pages',
            new_name='nb_visited_links',
        ),
    ]
