# Generated by Django 5.0.10 on 2024-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_historicalpruningmoderation_pruned_indices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='category',
            field=models.CharField(choices=[('new_schedules', 'New Schedules'), ('llm_error', 'Llm Error')], max_length=13),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='category',
            field=models.CharField(choices=[('new_schedules', 'New Schedules'), ('llm_error', 'Llm Error')], max_length=13),
        ),
    ]
