# Generated by Django 4.2 on 2023-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_nb_crawled_pages_crawling_nb_visited_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='confession_html_refined',
            field=models.TextField(null=True),
        ),
    ]
