# Generated by Django 5.0.11 on 2025-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_historicalparsingmoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='category',
            field=models.CharField(choices=[('new_schedules', 'New Schedules'), ('schedules_differ', 'Schedules Differ'), ('llm_error', 'Llm Error')], max_length=16),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='category',
            field=models.CharField(choices=[('new_schedules', 'New Schedules'), ('schedules_differ', 'Schedules Differ'), ('llm_error', 'Llm Error')], max_length=16),
        ),
    ]
