# Generated by Django 5.0.11 on 2025-01-24 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_historicalparsingmoderation_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('good', 'Good'), ('outdated', 'Outdated'), ('error', 'Error'), ('comment', 'Comment')], max_length=8)),
                ('error_type', models.CharField(choices=[('churches', 'Churches'), ('paragraphs', 'Paragraphs'), ('schedules', 'Schedules')], max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('ip_address_hash', models.CharField(max_length=64, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
