# Generated by Django 4.2 on 2023-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_crawling_success_crawling_nb_success_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
