# Generated by Django 4.2 on 2023-08-25 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_page_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='messesinfo_community_id',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='messesinfo_network_id',
        ),
        migrations.CreateModel(
            name='ParishSource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('messesinfo_network_id', models.CharField(max_length=100, null=True)),
                ('messesinfo_community_id', models.CharField(max_length=100, null=True, unique=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='home.parish')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='church',
            name='parish_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches', to='home.parishsource'),
        ),
    ]
