# Generated by Django 4.2 on 2023-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_parish_messesinfo_community_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishsource',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
