# Generated by Django 5.0.11 on 2025-02-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_historicalreportmoderation_reportmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalchurchmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalparishmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalparsingmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalpruningmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalreportmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalsentencemoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='historicalwebsitemoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parish_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='parsingmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsing_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='pruningmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pruning_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='reportmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='sentencemoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence_moderations', to='home.diocese'),
        ),
        migrations.AddField(
            model_name='websitemoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_moderations', to='home.diocese'),
        ),
    ]
