# Generated by Django 4.2 on 2023-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_parishsource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='parishsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
