# Generated by Django 4.2 on 2023-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_parish_name_alter_parishsource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='home_url',
            field=models.URLField(unique=True),
        ),
    ]
