# Generated by Django 4.2 on 2023-09-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_parish_home_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraping',
            name='confession_html_refined',
        ),
    ]
