# Generated by Django 5.0.11 on 2025-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_church_wikidata_id_historicalchurch_wikidata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('google_search', 'Google Search')], max_length=13),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('google_search', 'Google Search')], max_length=13),
        ),
    ]
