# Generated by Django 5.0.11 on 2025-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_historicalwebsitemoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsite',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('schedule_in_pdf', 'Schedule In Pdf'), ('javascript_required', 'Javascript Required'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200'), ('foreign_language', 'Foreign Language')], null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('schedule_in_pdf', 'Schedule In Pdf'), ('javascript_required', 'Javascript Required'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200'), ('foreign_language', 'Foreign Language')], null=True),
        ),
    ]
