# Generated by Django 4.2 on 2023-09-20 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_scraping_confession_html_refined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.TextField(unique=True)),
                ('is_confession', models.BooleanField()),
                ('is_schedule', models.BooleanField()),
                ('is_date', models.BooleanField()),
                ('is_period', models.BooleanField()),
                ('is_place', models.BooleanField()),
                ('is_spiritual', models.BooleanField()),
                ('is_other', models.BooleanField()),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
