# Generated by Django 4.2 on 2023-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='confession_html_pruned',
            field=models.TextField(null=True),
        ),
    ]
