# Generated by Django 5.0.11 on 2025-02-21 13:46

import scraping.parse.llm_client
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_historicalwebsite_unreliability_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OPENAI')], default=scraping.parse.llm_client.LLMProvider['OPENAI']),
        ),
        migrations.AddField(
            model_name='parsing',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OPENAI')], default=scraping.parse.llm_client.LLMProvider['OPENAI']),
        ),
    ]
