# Generated by Django 4.2.6 on 2023-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_scraping_confession_html_pruned'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='pruned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
