# Generated by Django 5.0.11 on 2025-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_crawling_recrawl_triggered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='home_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicaldiocese',
            name='home_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
