# Generated by Django 5.0.1 on 2024-01-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_scraping_pruned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='scraping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.scraping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
