# Generated by Django 5.0.11 on 2025-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_diocese_home_url_historicaldiocese_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('google_search', 'Google Search'), ('sched_conflict', 'Schedules Conflict')], max_length=16),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('google_search', 'Google Search'), ('sched_conflict', 'Schedules Conflict')], max_length=16),
        ),
    ]
