# Generated by Django 5.0.1 on 2024-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_churchmoderation_parishmoderation_scrapingmoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api')], max_length=8),
        ),
    ]
