# Generated by Django 5.0.11 on 2025-03-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_historicalwebsitemoderation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsitemoderation',
            name='conflict_church',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.church'),
        ),
        migrations.AddField(
            model_name='historicalwebsitemoderation',
            name='conflict_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='websitemoderation',
            name='conflict_church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_moderations', to='home.church'),
        ),
        migrations.AddField(
            model_name='websitemoderation',
            name='conflict_day',
            field=models.DateField(null=True),
        ),
    ]
