# Generated by Django 5.0.11 on 2025-03-12 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_historicalwebsitemoderation_conflict_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsings', to='home.website'),
        ),
    ]
