# Generated by Django 5.0.1 on 2024-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_churchmoderation_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
