# Generated by Django 5.0.1 on 2024-03-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_parish_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='marked_as_bug_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='marked_as_bug_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_marked_as_bug_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='marked_as_bug_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='marked_as_bug_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_marked_as_bug_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapingmoderation',
            name='marked_as_bug_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scrapingmoderation',
            name='marked_as_bug_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_marked_as_bug_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_validated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
