# Generated by Django 5.0.13 on 2025-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_searchhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs'), ('location_differs', 'Location Differs'), ('added_church', 'Added Church'), ('deleted_church', 'Deleted Church'), ('location_conflict', 'Location Conflict'), ('location_outlier', 'Location Outlier')], max_length=17),
        ),
        migrations.AlterField(
            model_name='historicalchurchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs'), ('location_differs', 'Location Differs'), ('added_church', 'Added Church'), ('deleted_church', 'Deleted Church'), ('location_conflict', 'Location Conflict'), ('location_outlier', 'Location Outlier')], max_length=17),
        ),
    ]
