# Generated by Django 5.0.1 on 2024-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_churchmoderation_marked_as_bug_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='bug_description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='bug_description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapingmoderation',
            name='bug_description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
