# Generated by Django 5.0.13 on 2025-04-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_churchmoderation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='main_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.report'),
        ),
    ]
