# Generated by Django 5.0.13 on 2025-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_report_main_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportmoderation',
            name='category',
            field=models.CharField(choices=[('good', 'Good'), ('outdated', 'Outdated'), ('error', 'Error'), ('comment', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reportmoderation',
            name='category',
            field=models.CharField(choices=[('good', 'Good'), ('outdated', 'Outdated'), ('error', 'Error'), ('comment', 'Comment')], max_length=16),
        ),
    ]
