# Generated by Django 5.0.1 on 2024-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_churchmoderation_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='confession_html_pruned',
            field=models.TextField(unique=True),
        ),
    ]
