# Generated by Django 5.0.1 on 2024-03-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_diocese_parish_diocese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='home.diocese'),
        ),
    ]
