# Generated by Django 5.0.13 on 2025-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_historicalreportmoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpage',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
