# Generated by Django 5.0.14 on 2025-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_historicalpage_url_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparish',
            name='messesinfo_community_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparish',
            name='messesinfo_network_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalparsing',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OPENAI')]),
        ),
        migrations.AlterField(
            model_name='parish',
            name='messesinfo_community_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='messesinfo_network_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OPENAI')]),
        ),
    ]
