# Generated by Admin on 2024-04-02 21:45

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_parish_diocese'),
    ]

    operations = [
        UnaccentExtension(),
    ]
