# Generated by Django 5.0.14 on 2025-04-14 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_historicalparish_messesinfo_community_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('crawling', 'Crawling'), ('scraping', 'Scraping')], max_length=8)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='home.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
