# Generated by Django 5.0.14 on 2025-04-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='error_type',
            field=models.CharField(blank=True, choices=[('churches', 'Churches'), ('paragraphs', 'Paragraphs'), ('schedules', 'Schedules')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='main_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.report'),
        ),
    ]
