# Generated by Django 5.0.14 on 2025-04-25 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_report_error_type_alter_report_main_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchIndexEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True, null=True)),
                ('start_time', models.TimeField(db_index=True, null=True)),
                ('indexed_end_time', models.TimeField(db_index=True, null=True)),
                ('displayed_end_time', models.TimeField(null=True)),
                ('is_explicitely_other', models.BooleanField(null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.church')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
