# Generated by Django 5.0.3 on 2024-04-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_deleted_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='scraping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations', to='home.scraping'),
        ),
    ]
