# Generated by Django 5.0.14 on 2025-04-24 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_report_error_type_alter_report_main_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteIndexEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(null=True)),
                ('is_explicitely_other', models.BooleanField()),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='home.church')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
