# Generated by Django 5.0.3 on 2024-04-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_page_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishsource',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='home.parish'),
        ),
    ]
