# Generated by Django 5.0.14 on 2025-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_churchindexevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchindexevent',
            name='has_been_moderated',
            field=models.BooleanField(null=True),
        ),
    ]
