# Generated by Django 5.0.14 on 2025-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_churchindexevent_has_been_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchindexevent',
            name='church_color',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
