# Generated by Django 5.0.14 on 2025-04-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_churchindexevent_church_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchindexevent',
            name='church_color',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='churchindexevent',
            name='day',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='churchindexevent',
            name='has_been_moderated',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='churchindexevent',
            name='indexed_end_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='churchindexevent',
            name='start_time',
            field=models.TimeField(db_index=True),
        ),
    ]
