# Generated by Django 5.0.3 on 2024-04-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_page_url_alter_parishsource_parish'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishsource',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='home.diocese'),
        ),
    ]
