# Generated by Django 5.0.3 on 2024-04-08 18:56

from django.db import migrations


def create_missing_parish_sources(apps, schema_editor):
    for church in apps.get_model('home', 'Church').objects.all():
        if church.parish_source is None:
            parish_source = apps.get_model('home', 'ParishSource').objects.create(
                name=church.parish.name,
                parish=church.parish,
                diocese=church.parish.diocese,
            )
            parish_source.save()
            church.parish_source = parish_source
            church.save()


def fill_parish_source_diocese(apps, schema_editor):
    for parish_source in apps.get_model('home', 'ParishSource').objects.all():
        if parish_source.diocese is None and parish_source.parish is not None:
            parish_source.diocese = parish_source.parish.diocese
            parish_source.save()

        elif parish_source.messesinfo_network_id is not None:
            try:
                diocese = apps.get_model('home', 'Diocese').objects.get(
                    messesinfo_network_id=parish_source.messesinfo_network_id)
                parish_source.diocese = diocese
                parish_source.save()
            except apps.get_model('home', 'Diocese').DoesNotExist:
                print(f'no diocese for network_id {parish_source.messesinfo_network_id}')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_parishsource_diocese'),
    ]

    operations = [
        migrations.RunPython(create_missing_parish_sources, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(fill_parish_source_diocese, reverse_code=migrations.RunPython.noop),
    ]
