# Generated by Django 5.0.14 on 2025-04-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_churchindexevent_church_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchindexevent',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='churchindexevent',
            unique_together={('church', 'day', 'start_time', 'displayed_end_time', 'is_explicitely_other')},
        ),
    ]
