# Generated by Django 5.0.3 on 2024-04-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_create_missing_parish_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishsource',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='home.diocese'),
        ),
    ]
