# Generated by Django 5.0.14 on 2025-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_churchindexevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsite',
            name='is_best_diocese_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalwebsite',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='is_best_diocese_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
