# Generated by Django 5.0.3 on 2024-04-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_parishsource_diocese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='diocese',
        ),
    ]
