# Generated by Django 5.0.14 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_historicalwebsite_is_best_diocese_hit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparish',
            name='messesinfo_community_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='messesinfo_community_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
