# Generated by Django 5.0.14 on 2025-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_historicalparish_messesinfo_community_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='trouverunemesse_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='church',
            name='trouverunemesse_slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='trouverunemesse_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='trouverunemesse_slug',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
