# Generated by Django 5.0.3 on 2024-04-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_parish_diocese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='parish_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='home.parishsource'),
        ),
    ]
