# Generated by Django 5.0.3 on 2024-04-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_church_parish_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='parish',
        ),
    ]
