# Generated by Django 5.0.14 on 2025-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_church_trouverunemesse_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalchurchmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalparishmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
    ]
