# Generated by Django 5.0.3 on 2024-04-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_church_parish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='parish',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='parishsource',
            old_name='parish',
            new_name='website',
        ),
    ]
