# Generated by Django 5.0.14 on 2025-06-03 19:06
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_churchmoderation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='city_search',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='name_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='city_search',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='name_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        TrigramExtension(),
    ]
