# Generated by Django 5.0.14 on 2025-06-05 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_churchllmname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchTrouverUneMesse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trouverunemesse_id', models.UUIDField(unique=True)),
                ('trouverunemesse_slug', models.CharField(max_length=200, unique=True)),
                ('original_name', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
