# Generated by Django 5.0.14 on 2025-06-05 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_churchtrouverunemesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchTrouverUneMesseLLMName',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_template_hash', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255, null=True)),
                ('trouverunemesse_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_names', to='home.churchtrouverunemesse')),
            ],
            options={
                'unique_together': {('trouverunemesse_church', 'prompt_template_hash')},
            },
        ),
    ]
