# Generated by Django 5.0.3 on 2024-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_rename_parish_crawling_website'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parish',
            new_name='Website',
        ),
    ]
