# Generated by Django 5.0.3 on 2024-04-23 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_rename_parish_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParishModeration',
            new_name='WebsiteModeration',
        ),
    ]
