# Generated by Django 5.0.14 on 2025-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_churchtrouverunemessellmname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalchurch',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
