# Generated by Django 5.0.14 on 2025-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_church_name_alter_historicalchurch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='trouverunemesse_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='trouverunemesse_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
