# Generated by Django 5.0.3 on 2024-04-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_websitemoderation_delete_parishmoderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitemoderation',
            old_name='other_parish',
            new_name='other_website',
        ),
        migrations.RenameField(
            model_name='websitemoderation',
            old_name='parish',
            new_name='website',
        ),
        migrations.AlterUniqueTogether(
            name='websitemoderation',
            unique_together={('website', 'category')},
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='marked_as_bug_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_marked_as_bug_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_validated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
