# Generated by Django 5.2.3 on 2025-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_church_trouverunemesse_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalchurchmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalparishmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse')], max_length=16),
        ),
    ]
