# Generated by Django 5.0.3 on 2024-04-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_rename_parishsource_parish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='home.diocese'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='home.website'),
        ),
    ]
