# Generated by Django 5.0.3 on 2024-05-26 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_parish_diocese_alter_parish_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('name_differs', 'Name Differs'), ('website_differs', 'Website Differs')], max_length=16)),
                ('source', models.CharField(choices=[('messesinfo', 'Messesinfo')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('home_url', models.URLField(unique=True)),
                ('marked_as_bug_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_marked_as_bug_by', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='home.parish')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parish_validated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parish', 'category', 'source')},
            },
        ),
    ]
