# Generated by Django 5.2.3 on 2025-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='human_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='llm_error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='llm_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='llm_provider',
            field=models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
