# Generated by Django 5.0.3 on 2024-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_parishmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishmoderation',
            name='similar_parishes',
            field=models.ManyToManyField(related_name='similar_moderations', to='home.parish'),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='category',
            field=models.CharField(choices=[('name_differs', 'Name Differs'), ('website_differs', 'Website Differs'), ('missing_parish', 'Missing Parish')], max_length=16),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='home_url',
            field=models.URLField(),
        ),
    ]
