# Generated by Django 5.2.3 on 2025-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_image_human_html_image_llm_error_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='prunings',
            field=models.ManyToManyField(related_name='images', to='home.pruning'),
        ),
    ]
