# Generated by Django 5.0.3 on 2024-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_parishmoderation_similar_parishes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='churchmoderation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='churchmoderation',
            unique_together={('church', 'category', 'source')},
        ),
    ]
