# Generated by Django 5.2.3 on 2025-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_image_ip_address_hash_image_user_image_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsite',
            name='enabled_for_crawling',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='enabled_for_crawling',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsite',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('schedule_in_pdf', 'Schedule In Pdf'), ('javascript_required', 'Javascript Required'), ('too_noisy_html', 'Too Noisy Html'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200'), ('foreign_language', 'Foreign Language')], null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('schedule_in_pdf', 'Schedule In Pdf'), ('javascript_required', 'Javascript Required'), ('too_noisy_html', 'Too Noisy Html'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200'), ('foreign_language', 'Foreign Language')], null=True),
        ),
    ]
