# Generated by Django 5.0.3 on 2024-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_churchmoderation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmoderation',
            name='source',
            field=models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre')], max_length=10),
        ),
    ]
