# Generated by Django 5.0.3 on 2024-05-28 18:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_churchmoderation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parishmoderation',
            name='home_url',
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_moderations', to='home.parish'),
        ),
        migrations.AddField(
            model_name='parishmoderation',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parish_moderations', to='home.website'),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs')], max_length=16),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
