# Generated by Django 5.2.3 on 2025-07-27 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_historicalwebsite_enabled_for_crawling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteForbiddenPath',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=300)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_paths', to='home.website')),
            ],
            options={
                'unique_together': {('website', 'path')},
            },
        ),
    ]
