# Generated by Django 5.0.3 on 2024-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_parishmoderation_home_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='similar_churches',
            field=models.ManyToManyField(related_name='similar_moderations', to='home.church'),
        ),
        migrations.AddField(
            model_name='churchmoderation',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs'), ('location_differs', 'Location Differs'), ('missing_church', 'Missing Church')], max_length=16),
        ),
    ]
