# Generated by Django 5.2.3 on 2025-08-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_websiteforbiddenpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='page_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_new', to='home.page'),
        ),
    ]
