# Generated by Django 5.2.3 on 2025-08-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_scraping_page_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='page_new',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_new', to='home.page'),
        ),
    ]
