# Generated by Django 5.2.3 on 2025-08-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_scraping_page_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpage',
            name='scraping',
        ),
        migrations.RemoveField(
            model_name='page',
            name='scraping',
        ),
    ]
