# Generated by Django 5.0.3 on 2024-06-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_church_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitemoderation',
            name='home_url',
        ),
        migrations.RemoveField(
            model_name='websitemoderation',
            name='name',
        ),
    ]
