# Generated by Django 5.2.3 on 2025-08-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_remove_historicalpage_scraping_remove_page_scraping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraping',
            old_name='page_new',
            new_name='page',
        ),
    ]
