# Generated by Django 5.0.3 on 2024-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_remove_websitemoderation_home_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemoderation',
            name='home_url',
            field=models.URLField(null=True),
        ),
    ]
