# Generated by Django 5.2.3 on 2025-08-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_rename_page_new_scraping_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping', to='home.page'),
        ),
    ]
