# Generated by Django 5.0.3 on 2024-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_websitemoderation_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
