# Generated by Django 5.2.3 on 2025-08-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_scraping_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession')], default='action', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession')], default='action', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='confession_classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='human_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='human_schedule',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='human_specifier',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='ml_schedule',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='ml_specifier',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='schedule_classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='specifier_classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='confession_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confession_sentences', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='human_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='human_schedule',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='human_specifier',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='ml_schedule',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='ml_specifier',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='schedule_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_sentences', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='specifier_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifier_sentences', to='home.classifier'),
        ),
    ]
