# Generated by Django 5.0.3 on 2024-06-12 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_church_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326, unique=True),
        ),
    ]
