# Generated by Django 5.2.3 on 2025-08-01 10:09

import home.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_classifier_target_historicalclassifier_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='different_labels',
            field=models.JSONField(),
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='different_labels',
            field=models.JSONField(),
        ),
    ]
