# Generated by Django 5.0.3 on 2024-06-12 15:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_church_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmoderation',
            name='messesinfo_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='category',
            field=models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs'), ('location_differs', 'Location Differs'), ('added_church', 'Added Church'), ('deleted_church', 'Deleted Church'), ('location_conflict', 'Location Conflict')], max_length=17),
        ),
    ]
