# Generated by Django 5.0.3 on 2024-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_churchmoderation_messesinfo_id_alter_church_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(),
        ),
    ]
