# Generated by Django 5.2.3 on 2025-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_historicalsentencemoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='different_labels',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='different_labels',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession')], max_length=10),
        ),
    ]
