# Generated by Django 5.2.3 on 2025-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_classifier_different_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_schedule',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_specifier',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_schedule',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_specifier',
            field=models.BooleanField(),
        ),
    ]
