# Generated by Django 5.2.3 on 2025-08-03 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_historicalsentence_ml_confession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpruning',
            name='v2_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='pruning',
            name='v2_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
    ]
