# Generated by Django 5.0.3 on 2024-07-13 18:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_historicalchurch_historicaldiocese_historicalparish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChurchModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('loc_null', 'Location Null'), ('loc_api', 'Location From Api'), ('name_differs', 'Name Differs'), ('parish_differs', 'Parish Differs'), ('location_differs', 'Location Differs'), ('added_church', 'Added Church'), ('deleted_church', 'Deleted Church'), ('location_conflict', 'Location Conflict')], max_length=17)),
                ('source', models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre')], max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('messesinfo_id', models.CharField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.church')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.parish')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical church moderation',
                'verbose_name_plural': 'historical church moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParishModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('name_differs', 'Name Differs'), ('website_differs', 'Website Differs'), ('added_parish', 'Added Parish'), ('deleted_parish', 'Deleted Parish')], max_length=16)),
                ('source', models.CharField(choices=[('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre')], max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.parish')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
            ],
            options={
                'verbose_name': 'historical parish moderation',
                'verbose_name_plural': 'historical parish moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWebsiteModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict')], max_length=11)),
                ('home_url', models.URLField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('other_website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
            ],
            options={
                'verbose_name': 'historical website moderation',
                'verbose_name_plural': 'historical website moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
