# Generated by Django 5.0.3 on 2024-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_historicalchurchmoderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4, null=True),
        ),
    ]
