# Generated by Django 5.2.3 on 2025-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_historicalpruning_v2_indices_pruning_v2_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='category',
            field=models.CharField(choices=[('new_pruned_html', 'New Pruned Html'), ('v2_diff_human', 'V2 Diff Human'), ('v2_diff_v1', 'V2 Diff V1')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='category',
            field=models.CharField(choices=[('new_pruned_html', 'New Pruned Html'), ('v2_diff_human', 'V2 Diff Human'), ('v2_diff_v1', 'V2 Diff V1')], max_length=16),
        ),
    ]
