# Generated by Django 5.0.3 on 2024-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_sentence_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='is_confession',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_date',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_period',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_place',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_schedule',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_spiritual',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4),
        ),
    ]
