# Generated by Django 5.2.3 on 2025-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_historicalpruningmoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('crawling', 'Crawling'), ('scraping', 'Scraping'), ('parsing', 'Parsing')], max_length=8),
        ),
    ]
