# Generated by Django 5.2.3 on 2025-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='human_confession',
            field=models.CharField(choices=[('start', 'START'), ('hold', 'HOLD'), ('hide', 'HIDE'), ('stop', 'STOP'), ('show', 'SHOW')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('hold', 'HOLD'), ('hide', 'HIDE'), ('stop', 'STOP'), ('show', 'SHOW')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='human_confession',
            field=models.CharField(choices=[('start', 'START'), ('hold', 'HOLD'), ('hide', 'HIDE'), ('stop', 'STOP'), ('show', 'SHOW')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_confession',
            field=models.CharField(choices=[('start', 'START'), ('hold', 'HOLD'), ('hide', 'HIDE'), ('stop', 'STOP'), ('show', 'SHOW')], max_length=5),
        ),
    ]
