# Generated by Django 5.0.7 on 2024-07-19 07:14

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_remove_sentence_is_confession_and_more'),
    ]

    operations = [
        VectorExtension()
    ]
