# Generated by Django 5.0.7 on 2024-07-19 07:20

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_add_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transformer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prod', 'Prod')], max_length=5)),
                ('pickle', models.CharField()),
                ('accuracy', models.FloatField()),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.CharField(choices=[('human', 'Human'), ('ml', 'Ml')], default='human', max_length=5),
        ),
        migrations.AddField(
            model_name='sentence',
            name='transformer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='home.classifier'),
        ),
    ]
