# Generated by Django 5.0.7 on 2024-07-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_classifier_sentence_embedding_sentence_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='scraping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='home.scraping'),
        ),
    ]
