# Generated by Django 5.2.3 on 2025-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_historicalsentence_human_confession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
    ]
