# Generated by Django 5.0.7 on 2024-07-21 15:48

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_scrapingmoderation_scraping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='scraping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='home.scraping'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.CharField(choices=[('human', 'Human'), ('ml', 'Ml')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='transformer_name',
            field=models.CharField(max_length=100),
        ),
    ]
