# Generated by Django 5.2.3 on 2025-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_alter_historicalsentencemoderation_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('specifier_mismatch', 'Specifier Mismatch'), ('schedules_mismatch', 'Schedules Mismatch'), ('confession_mismatch', 'Confession Mismatch'), ('confession_outlier', 'Confession Outlier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('specifier_mismatch', 'Specifier Mismatch'), ('schedules_mismatch', 'Schedules Mismatch'), ('confession_mismatch', 'Confession Mismatch'), ('confession_outlier', 'Confession Outlier')], max_length=20),
        ),
    ]
