# Generated by Django 5.2.3 on 2025-09-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_alter_historicalsentencemoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('confession_outlier', 'Confession Outlier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('confession_outlier', 'Confession Outlier')], max_length=20),
        ),
    ]
