# Generated by Django 5.2.3 on 2025-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_historicalsentencemoderation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('timeout', 'Timeout'), ('failure', 'Failure')], max_length=8, null=True),
        ),
    ]
