# Generated by Django 5.0.7 on 2024-07-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_historicalscrapingmoderation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalScrapingModeration',
        ),
    ]
