# Generated by Django 5.2.3 on 2025-09-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsentence',
            name='human_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='ml_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='temporal_classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='human_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='ml_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='temporal_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_sentences', to='home.classifier'),
        ),
    ]
