# Generated by Django 5.0.7 on 2024-07-21 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_delete_historicalscrapingmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='scrapingmoderation',
            name='confession_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scrapingmoderation',
            name='indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
    ]
