# Generated by Django 5.2.3 on 2025-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_historicalsentence_human_temporal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession'), ('temporal', 'Temporal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('specifier', 'Specifier'), ('schedule', 'Schedule'), ('confession', 'Confession'), ('temporal', 'Temporal')], max_length=10),
        ),
    ]
