# Generated by Django 5.0.7 on 2024-07-21 21:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_scraping_indices_scrapingmoderation_confession_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingmoderation',
            name='confession_html_pruned',
        ),
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='confession_html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scrapingmoderation',
            name='indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None),
        ),
    ]
