# Generated by Django 5.2.3 on 2025-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_classifier_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_temporal',
            field=models.CharField(choices=[('none', 'NONE'), ('sched', 'SCHED'), ('spec', 'SPEC')], max_length=5),
        ),
    ]
