# Generated by Django 5.2.3 on 2025-09-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_historicalsentence_ml_temporal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='human_schedule',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='human_specifier',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='ml_schedule',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='ml_specifier',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='schedule_classifier',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='specifier_classifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='human_schedule',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='human_specifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='ml_schedule',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='ml_specifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='schedule_classifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='specifier_classifier',
        ),
    ]
