# Generated by Django 5.0.7 on 2024-08-04 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_pruning_scraping_pruning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapingmoderation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scrapingmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='scrapingmoderation',
            name='scraping',
        ),
        migrations.RemoveField(
            model_name='scrapingmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='confession_html_pruned',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='indices',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='pruned_at',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='scraping',
        ),
        migrations.AddField(
            model_name='sentence',
            name='pruning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pruning'),
        ),
        migrations.AlterField(
            model_name='pruning',
            name='extracted_html',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pruning',
            name='pruned_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pruning',
            name='pruned_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='confession_html',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalPruningModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('new_pruned_html', 'New Pruned Html')], max_length=16)),
                ('pruned_html', models.TextField()),
                ('pruned_indices', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pruning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.pruning')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pruning moderation',
                'verbose_name_plural': 'historical pruning moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PruningModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('new_pruned_html', 'New Pruned Html')], max_length=16)),
                ('pruned_html', models.TextField()),
                ('pruned_indices', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('marked_as_bug_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruning_marked_as_bug_by', to=settings.AUTH_USER_MODEL)),
                ('pruning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='home.pruning')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruning_validated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pruning', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalScrapingModeration',
        ),
        migrations.DeleteModel(
            name='ScrapingModeration',
        ),
    ]
