# Generated by Django 5.2.3 on 2025-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_remove_historicalsentence_human_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
    ]
