# Generated by Django 5.2.3 on 2025-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_classifier_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsite',
            name='home_url',
            field=models.URLField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='home_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
