# Generated by Django 5.0.7 on 2024-08-04 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_scrapingmoderation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='pruned_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='pruned_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='pruned_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='pruned_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=None),
        ),
    ]
