# Generated by Django 5.0.7 on 2024-08-04 19:55

from django.db import migrations, models


def update_and_delete(apps, schema_editor):
    Scraping = apps.get_model('home', 'Scraping')
    Pruning = apps.get_model('home', 'Pruning')
    Scraping.objects.all().update(pruning=None)
    Pruning.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_historicalpruningmoderation_pruned_html_and_more'),
    ]

    operations = [
        migrations.RunPython(update_and_delete),
        migrations.AddField(
            model_name='pruning',
            name='extracted_html_hash',
            field=models.CharField(default=123, editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruning',
            name='extracted_html',
            field=models.TextField(editable=False),
        ),
    ]
