# Generated by Django 5.2.3 on 2025-10-27 18:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_alter_historicalwebsitemoderation_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={},
        ),
        migrations.AddIndex(
            model_name='church',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='home_church_locatio_11d715_gist'),
        ),
    ]
