# Generated by Django 5.2.3 on 2025-10-27 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_alter_church_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE home_church
                ALTER
                COLUMN location 
                    TYPE geometry(Point, 4326) 
                    USING location::geometry(Point, 4326);
                """,
            reverse_sql="""
                        ALTER TABLE home_church
                        ALTER
                        COLUMN location 
                    TYPE geography(Point, 4326) 
                    USING location::geography(Point, 4326);
                        """
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE home_historicalchurch
                ALTER
                COLUMN location 
                    TYPE geometry(Point, 4326) 
                    USING location::geometry(Point, 4326);
                """,
            reverse_sql="""
                        ALTER TABLE home_historicalchurch
                        ALTER
                        COLUMN location 
                    TYPE geography(Point, 4326) 
                    USING location::geography(Point, 4326);
                        """
        ),
    ]
