# Generated by Django 5.0.7 on 2024-08-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_alter_scraping_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='pruning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapings', to='home.pruning'),
        ),
    ]
