# Generated by Django 5.2.3 on 2025-10-31 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_alter_church_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='human_json_version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='llm_json_version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='parsing',
            name='human_json_version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AddField(
            model_name='parsing',
            name='llm_json_version',
            field=models.CharField(default='v1.0', max_length=6),
        ),
        migrations.AlterField(
            model_name='church',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalchurch',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
