# Generated by Django 5.2.8 on 2025-11-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_historicalparsing_human_json_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsentence',
            old_name='confession_classifier',
            new_name='confession_legacy_classifier',
        ),
        migrations.RenameField(
            model_name='historicalsentence',
            old_name='human_confession',
            new_name='human_confession_legacy',
        ),
        migrations.RenameField(
            model_name='historicalsentence',
            old_name='ml_confession',
            new_name='ml_confession_legacy',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='confession_classifier',
            new_name='confession_legacy_classifier',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='human_confession',
            new_name='human_confession_legacy',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='ml_confession',
            new_name='ml_confession_legacy',
        ),
    ]
