# Generated by Django 5.2.8 on 2025-11-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_rename_confession_classifier_historicalsentence_confession_legacy_classifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsentence',
            name='human_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='ml_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='human_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='ml_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession_legacy', 'Confession Legacy'), ('confession', 'Confession')], max_length=17),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession_legacy', 'Confession Legacy'), ('confession', 'Confession')], max_length=17),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='confession_legacy_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confession_legacy_sentences', to='home.classifier'),
        ),
    ]
