# Generated by Django 5.0.8 on 2024-08-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_historicalsentencemoderation_sentencemoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='sentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4, null=True),
        ),
    ]
