# Generated by Django 5.2.8 on 2025-11-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_historicalsentence_human_confession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsentence',
            name='confession_new_classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.classifier'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='confession_new_classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confession_new_sentences', to='home.classifier'),
        ),
    ]
