# Generated by Django 5.0.8 on 2024-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_historicalsentencemoderation_other_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('stop', 'Stop')], max_length=4),
        ),
    ]
