# Generated by Django 5.2.8 on 2025-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_historicalsentence_confession_new_classifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='ml_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='ml_confession',
            field=models.CharField(choices=[('event', 'EVENT'), ('neutral', 'NEUTRAL'), ('other', 'OTHER')], max_length=7),
        ),
    ]
