# Generated by Django 5.2.8 on 2025-11-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_alter_historicalsentence_ml_confession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='confession_legacy_classifier',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='human_confession_legacy',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='ml_confession_legacy',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='confession_legacy_classifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='human_confession_legacy',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='ml_confession_legacy',
        ),
    ]
