# Generated by Django 5.2.8 on 2025-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_remove_historicalsentence_confession_legacy_classifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('action', 'Action'), ('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
    ]
