# Generated by Django 5.2.8 on 2025-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_alter_classifier_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsite',
            name='oclocher_organization_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='oclocher_organization_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
