# Generated by Django 5.2.8 on 2025-11-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_historicalwebsite_oclocher_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('hu_diocese', 'Home Url Diocese'), ('google_search', 'Google Search'), ('sched_conflict', 'Schedules Conflict'), ('oclocher_conflict', 'Oclocher Conflict')], max_length=32),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='category',
            field=models.CharField(choices=[('name_concat', 'Name Concatenated'), ('name_websit', 'Name Website Title'), ('hu_no_resp', 'Home Url No Response'), ('hu_no_conf', 'Home Url No Confession'), ('hu_conflict', 'Home Url Conflict'), ('hu_too_long', 'Home Url Too Long'), ('hu_diocese', 'Home Url Diocese'), ('google_search', 'Google Search'), ('sched_conflict', 'Schedules Conflict'), ('oclocher_conflict', 'Oclocher Conflict')], max_length=32),
        ),
    ]
