# Generated by Django 5.2.8 on 2025-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_alter_historicalwebsitemoderation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='oclocher_organization_id',
        ),
        migrations.RemoveField(
            model_name='website',
            name='oclocher_organization_id',
        ),
    ]
