# Generated by Django 5.0.8 on 2024-09-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_remove_scraping_confession_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpage',
            old_name='last_validated_at',
            new_name='pruning_last_validated_at',
        ),
        migrations.RenameField(
            model_name='historicalpage',
            old_name='validation_counter',
            new_name='pruning_validation_counter',
        ),
        migrations.RenameField(
            model_name='historicalwebsite',
            old_name='last_validated_at',
            new_name='pruning_last_validated_at',
        ),
        migrations.RenameField(
            model_name='historicalwebsite',
            old_name='validation_counter',
            new_name='pruning_validation_counter',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='last_validated_at',
            new_name='pruning_last_validated_at',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='validation_counter',
            new_name='pruning_validation_counter',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='last_validated_at',
            new_name='pruning_last_validated_at',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='validation_counter',
            new_name='pruning_validation_counter',
        ),
    ]
