# Generated by Django 5.0.8 on 2024-09-04 13:18

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_rename_last_validated_at_historicalpage_pruning_last_validated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParsing',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('church_desc_by_id', models.JSONField()),
                ('error_detail', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pruning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.pruning')),
            ],
            options={
                'verbose_name': 'historical parsing',
                'verbose_name_plural': 'historical parsings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church_desc_by_id', models.JSONField()),
                ('error_detail', models.TextField(null=True)),
                ('pruning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsings', to='home.pruning')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSchedule',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('church_id', models.SmallIntegerField(null=True)),
                ('rdates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('exdates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('rrules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('exrules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('duration_in_minutes', models.SmallIntegerField(null=True)),
                ('during_school_holidays', models.BooleanField(null=True)),
                ('possible_by_appointment', models.BooleanField()),
                ('is_related_to_mass', models.BooleanField()),
                ('is_related_to_adoration', models.BooleanField()),
                ('is_related_to_permanence', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parsing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.parsing')),
            ],
            options={
                'verbose_name': 'historical schedule',
                'verbose_name_plural': 'historical schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church_id', models.SmallIntegerField(null=True)),
                ('rdates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('exdates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('rrules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('exrules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('duration_in_minutes', models.SmallIntegerField(null=True)),
                ('during_school_holidays', models.BooleanField(null=True)),
                ('possible_by_appointment', models.BooleanField()),
                ('is_related_to_mass', models.BooleanField()),
                ('is_related_to_adoration', models.BooleanField()),
                ('is_related_to_permanence', models.BooleanField()),
                ('parsing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.parsing')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
