# Generated by Django 5.0.8 on 2024-09-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_historicalparsing_parsing_historicalschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='llm_model',
            field=models.CharField(default='fake', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='prompt_template_hash',
            field=models.CharField(default='fake', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsing',
            name='llm_model',
            field=models.CharField(default='fake', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsing',
            name='prompt_template_hash',
            field=models.CharField(default='fake', max_length=32),
            preserve_default=False,
        ),
    ]
