# Generated by Django 5.0.8 on 2024-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_alter_parsing_options_alter_parsing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparsingmoderation',
            name='validated_schedules_list',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='parsingmoderation',
            name='validated_schedules_list',
            field=models.JSONField(null=True),
        ),
    ]
