# Generated by Django 5.2.9 on 2026-01-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_historicalscraping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChurchIndexEvent',
        ),
    ]
