# Generated by Django 5.0.8 on 2024-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_alter_historicalparsingmoderation_validated_schedules_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschedule',
            name='is_related_to_adoration',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='is_related_to_mass',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='is_related_to_permanence',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='possible_by_appointment',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_related_to_adoration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_related_to_mass',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_related_to_permanence',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='possible_by_appointment',
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='is_related_to_adoration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='is_related_to_mass',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='is_related_to_permanence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='possible_by_appointment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='is_related_to_adoration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='is_related_to_mass',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='is_related_to_permanence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='possible_by_appointment',
            field=models.BooleanField(null=True),
        ),
    ]
