# Generated by Django 5.2.9 on 2026-01-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_delete_churchindexevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparsing',
            name='website',
        ),
        migrations.RemoveField(
            model_name='parsing',
            name='website',
        ),
    ]
