# Generated by Django 5.0.8 on 2024-09-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_remove_historicalschedule_is_related_to_adoration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='exdates',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='exrules',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='rdates',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='rrules',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exdates',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exrules',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rdates',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rrules',
            field=models.CharField(),
        ),
    ]
