# Generated by Django 5.2.9 on 2026-01-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_remove_historicalparsing_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsitemoderation',
            name='home_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websitemoderation',
            name='home_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
