# Generated by Django 5.0.8 on 2024-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_alter_historicalschedule_exdates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalschedule',
            old_name='exrules',
            new_name='exrule',
        ),
        migrations.RenameField(
            model_name='historicalschedule',
            old_name='rrules',
            new_name='rrule',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='exrules',
            new_name='exrule',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='rrules',
            new_name='rrule',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='exdates',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='rdates',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='exdates',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='rdates',
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='pruning_last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwebsite',
            name='pruning_last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='pruning_last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='pruning_last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
