# Generated by Django 5.2.9 on 2026-01-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_alter_historicalwebsitemoderation_home_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpage',
            name='parsing_last_validated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='parsing_validation_counter',
        ),
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='parsing_last_validated_at',
        ),
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='parsing_validation_counter',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parsing_last_validated_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parsing_validation_counter',
        ),
        migrations.RemoveField(
            model_name='website',
            name='parsing_last_validated_at',
        ),
        migrations.RemoveField(
            model_name='website',
            name='parsing_validation_counter',
        ),
    ]
