# Generated by Django 5.2.9 on 2026-01-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_remove_historicalpage_parsing_last_validated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsing',
            name='prunings',
        ),
    ]
