# Generated by Django 5.0.8 on 2024-09-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_rename_exrules_historicalschedule_exrule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parsing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalparsing',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parsings', to='home.website'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='parsing',
            unique_together={('website', 'pruning')},
        ),
    ]
