# Generated by Django 5.2.9 on 2026-01-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_remove_parsing_prunings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpruning',
            name='pruned_indices',
        ),
        migrations.RemoveField(
            model_name='pruning',
            name='pruned_indices',
        ),
    ]
