# Generated by Django 5.0.8 on 2024-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_alter_parsing_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparsing',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='exrule',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='rrule',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exrule',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rrule',
            field=models.CharField(null=True),
        ),
    ]
