# Generated by Django 5.0.8 on 2024-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_alter_historicalparsing_error_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='exrule',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='rrule',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exrule',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rrule',
            field=models.CharField(blank=True, default=''),
        ),
    ]
