# Generated by Django 5.2.9 on 2026-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_remove_historicalpruning_pruned_indices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('crawling', 'Crawling'), ('scraping', 'Scraping'), ('pruning', 'Pruning'), ('parsing', 'Parsing')], max_length=8),
        ),
    ]
