# Generated by Django 5.2.9 on 2026-01-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_alter_log_type'),
        ('scheduling', '0007_historicalparsingmoderation_parsingmoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finetunedllm',
            name='parsing_moderations',
            field=models.ManyToManyField(related_name='fine_tuned_llms',
                                         to='scheduling.parsingmoderation'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='HistoricalParsingModeration'),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='ParsingModeration'),
            ],
        ),
    ]
