# Generated by Django 5.0.8 on 2024-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_alter_historicalschedule_exrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='exrule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='rrule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exrule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rrule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
