# Generated by Django 5.2.9 on 2026-01-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_remove_historicalparsingmoderation_diocese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscraping',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scraping',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
