# Generated by Django 5.2.9 on 2026-01-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_historicalscraping_url_scraping_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscraping',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website'),
        ),
        migrations.AddField(
            model_name='scraping',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='home.website'),
        ),
    ]
