# Generated by Django 5.0.8 on 2024-09-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_alter_historicalschedule_exrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparsing',
            name='has_seasonal_events',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='parsing',
            name='has_seasonal_events',
            field=models.BooleanField(null=True),
        ),
    ]
