# Generated by Django 5.2.9 on 2026-01-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_historicalscraping_website_scraping_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping', to='home.page'),
        ),
    ]
