# Generated by Django 5.0.8 on 2024-09-29 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_historicalparsing_has_seasonal_events_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalparsing',
            old_name='has_seasonal_events',
            new_name='will_be_seasonal_events',
        ),
        migrations.RenameField(
            model_name='parsing',
            old_name='has_seasonal_events',
            new_name='will_be_seasonal_events',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='during_school_holidays',
        ),
        migrations.RemoveField(
            model_name='historicalschedule',
            name='exrule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='during_school_holidays',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='exrule',
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='exclude_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='include_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='exclude_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='include_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], default=[], size=None),
            preserve_default=False,
        ),
    ]
