# Generated by Django 5.2.9 on 2026-01-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_alter_scraping_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraping',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='scraping',
            unique_together={('url', 'website')},
        ),
    ]
