# Generated by Django 5.0.8 on 2024-10-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_rename_has_seasonal_events_historicalparsing_will_be_seasonal_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='exrule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exrule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
