# Generated by Django 5.2.9 on 2026-01-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_alter_scraping_options_and_more'),
        ('attaching', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='image',
            name='prunings',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='image',
            name='user',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='image',
            name='website',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
            name='HistoricalImage',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
            name='Image',
        )]),
    ]
