# Generated by Django 5.2.9 on 2026-01-19 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_remove_image_prunings_remove_image_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscraping',
            name='page',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='page',
        ),
        migrations.AlterField(
            model_name='historicalscraping',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='home.website'),
        ),
    ]
