# Generated by Django 5.2.9 on 2026-01-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_remove_historicalscraping_page_remove_scraping_page_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='page',
            name='website',
        ),
        migrations.DeleteModel(
            name='HistoricalPage',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
