# Generated by Django 5.0.9 on 2024-10-12 22:45

import home.models.custom_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_alter_historicalschedule_exclude_periods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='exclude_periods',
            field=home.models.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], max_length=16), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='include_periods',
            field=home.models.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], max_length=16), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exclude_periods',
            field=home.models.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], max_length=16), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='include_periods',
            field=home.models.custom_fields.ChoiceArrayField(base_field=models.CharField(choices=[('january', 'JANUARY'), ('february', 'FEBRUARY'), ('march', 'MARCH'), ('april', 'APRIL'), ('may', 'MAY'), ('june', 'JUNE'), ('july', 'JULY'), ('august', 'AUGUST'), ('september', 'SEPTEMBER'), ('october', 'OCTOBER'), ('november', 'NOVEMBER'), ('december', 'DECEMBER'), ('advent', 'ADVENT'), ('lent', 'LENT'), ('school_holidays', 'SCHOOL_HOLIDAYS')], max_length=16), blank=True, size=None),
        ),
        migrations.CreateModel(
            name='FineTunedLLM',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('fine_tuning', 'Fine Tuning'), ('failed', 'Failed'), ('draft', 'Draft'), ('prod', 'Prod')], max_length=12)),
                ('dataset_name', models.CharField(max_length=100)),
                ('base_model', models.CharField(max_length=100)),
                ('fine_tune_job_id', models.CharField(max_length=100)),
                ('fine_tuned_model', models.CharField(max_length=100, null=True)),
                ('error_detail', models.TextField(null=True)),
                ('parsing_moderations', models.ManyToManyField(related_name='fine_tuned_llms', to='home.parsingmoderation')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
