# Generated by Django 5.2.9 on 2026-01-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_alter_page_unique_together_remove_page_website_and_more'),
        ('scheduling', '0009_historicalparsing_parsing_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='historicalparsing',
            name='history_user',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
            name='Parsing',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
            name='HistoricalParsing',
        )]),
    ]
