# Generated by Django 5.2.9 on 2026-01-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_remove_historicalparsing_history_user_delete_parsing_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.DeleteModel(
            name='FineTunedLLM',
        )]),
    ]
