# Generated by Django 5.0.9 on 2024-10-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_alter_parsing_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparsing',
            name='pruning',
        ),
        migrations.RemoveField(
            model_name='historicalparsing',
            name='website',
        ),
        migrations.RemoveField(
            model_name='parsing',
            name='pruning',
        ),
        migrations.RemoveField(
            model_name='parsing',
            name='website',
        ),
        migrations.AddField(
            model_name='parsing',
            name='prunings',
            field=models.ManyToManyField(related_name='parsings', to='home.pruning'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='websites',
            field=models.ManyToManyField(related_name='parsings', to='home.website'),
        ),
    ]
