# Generated by Django 5.0.9 on 2024-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_remove_historicalparsing_pruning_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parsing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalparsing',
            name='current_year',
            field=models.SmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='current_year',
            field=models.SmallIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='parsing',
            unique_together={('truncated_html_hash', 'church_desc_by_id', 'current_year')},
        ),
    ]
