# Generated by Django 5.2.9 on 2026-01-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_delete_finetunedllm'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='report',
            name='main_report',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
            model_name='report',
            name='user',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='report',
            name='website',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='reportmoderation',
            name='report',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.AlterUniqueTogether(
            name='reportmoderation',
            unique_together=None,
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='reportmoderation',
            name='diocese',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='reportmoderation',
            name='marked_as_bug_by',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='reportmoderation',
            name='validated_by',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.RemoveField(
            model_name='searchhit',
            name='user',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(
            name='HistoricalReportModeration',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(
            name='Report',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(
            name='ReportModeration',
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(
            name='SearchHit',
        )]),
    ]
