# Generated by Django 5.0.9 on 2024-10-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_remove_schedule_parsing_historicaloneoffschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloneoffschedule',
            old_name='weekday',
            new_name='weekday_iso8601',
        ),
        migrations.RenameField(
            model_name='oneoffschedule',
            old_name='weekday',
            new_name='weekday_iso8601',
        ),
    ]
