# Generated by Django 5.2.9 on 2026-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0003_alter_image_prunings'),
        ('home', '0119_remove_sentence_classifier_and_more'),
        ('scheduling', '0014_classifier_pruning_historicalclassifier_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='scraping',
            name='prunings',
            field=models.ManyToManyField(related_name='scrapings', to='scheduling.pruning'),
        ),
        migrations.DeleteModel(
            name='Classifier',
        ),
        migrations.DeleteModel(
            name='HistoricalClassifier',
        ),
        migrations.DeleteModel(
            name='HistoricalPruning',
        ),
        migrations.DeleteModel(
            name='HistoricalPruningModeration',
        ),
        migrations.DeleteModel(
            name='HistoricalSentence',
        ),
        migrations.DeleteModel(
            name='HistoricalSentenceModeration',
        ),
        migrations.DeleteModel(
            name='Pruning',
        ),
        migrations.DeleteModel(
            name='PruningModeration',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='SentenceModeration',
        ),
    ])]
