# Generated by Django 5.0.9 on 2024-11-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_rename_weekday_historicaloneoffschedule_weekday_iso8601_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloneoffschedule',
            old_name='is_exception_rule',
            new_name='is_cancellation',
        ),
        migrations.RenameField(
            model_name='historicalregularschedule',
            old_name='is_exception_rule',
            new_name='is_cancellation',
        ),
        migrations.RenameField(
            model_name='oneoffschedule',
            old_name='is_exception_rule',
            new_name='is_cancellation',
        ),
        migrations.RenameField(
            model_name='regularschedule',
            old_name='is_exception_rule',
            new_name='is_cancellation',
        ),
        migrations.RemoveField(
            model_name='historicaloneoffschedule',
            name='start_isoformat',
        ),
        migrations.RemoveField(
            model_name='historicalparsing',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='oneoffschedule',
            name='start_isoformat',
        ),
        migrations.AlterUniqueTogether(
            name='parsing',
            unique_together={('truncated_html_hash', 'church_desc_by_id')},
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='end_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='liturgical_day',
            field=models.CharField(blank=True, choices=[('ash_wednesday', 'ASH_WEDNESDAY'), ('palm_sunday', 'PALM_SUNDAY'), ('holy_monday', 'HOLY_MONDAY'), ('holy_tuesday', 'HOLY_TUESDAY'), ('holy_wednesday', 'HOLY_WEDNESDAY'), ('maundy_thursday', 'MAUNDY_THURSDAY'), ('good_friday', 'GOOD_FRIDAY'), ('holy_saturday', 'HOLY_SATURDAY'), ('easter_sunday', 'EASTER_SUNDAY'), ('ascension', 'ASCENSION'), ('pentecost', 'PENTECOST')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='start_time_iso8601',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaloneoffschedule',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregularschedule',
            name='end_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalregularschedule',
            name='start_time_iso8601',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='end_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='liturgical_day',
            field=models.CharField(blank=True, choices=[('ash_wednesday', 'ASH_WEDNESDAY'), ('palm_sunday', 'PALM_SUNDAY'), ('holy_monday', 'HOLY_MONDAY'), ('holy_tuesday', 'HOLY_TUESDAY'), ('holy_wednesday', 'HOLY_WEDNESDAY'), ('maundy_thursday', 'MAUNDY_THURSDAY'), ('good_friday', 'GOOD_FRIDAY'), ('holy_saturday', 'HOLY_SATURDAY'), ('easter_sunday', 'EASTER_SUNDAY'), ('ascension', 'ASCENSION'), ('pentecost', 'PENTECOST')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='start_time_iso8601',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oneoffschedule',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularschedule',
            name='end_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='regularschedule',
            name='start_time_iso8601',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='parsing',
            name='current_year',
        ),
    ]
