# Generated by Django 5.2.9 on 2026-01-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
        ('home', '0120_alter_scraping_prunings_delete_classifier_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='website',
            name='crawling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website', to='crawling.crawling'),
        ),
        migrations.AlterField(
            model_name='historicalwebsite',
            name='crawling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crawling.crawling'),
        ),
        migrations.RemoveField(
            model_name='historicalscraping',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalscraping',
            name='website',
        ),
        migrations.AlterUniqueTogether(
            name='scraping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='prunings',
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='website',
        ),
        migrations.AlterUniqueTogether(
            name='websiteforbiddenpath',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='websiteforbiddenpath',
            name='website',
        ),
        migrations.DeleteModel(
            name='Crawling',
        ),
        migrations.DeleteModel(
            name='HistoricalScraping',
        ),
        migrations.DeleteModel(
            name='Scraping',
        ),
        migrations.DeleteModel(
            name='WebsiteForbiddenPath',
        ),
    ])]
