# Generated by Django 5.2.9 on 2026-01-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_alter_website_crawling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
