# Generated by Django 5.0.9 on 2024-11-01 23:10

import django.db.models.deletion
import simple_history.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_historicalpage_parsing_last_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='parsing',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.parsing'),
        ),
        migrations.AlterField(
            model_name='historicalregularschedule',
            name='parsing',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.parsing'),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='parsing',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_off_schedules', to='home.parsing'),
        ),
        migrations.AlterField(
            model_name='regularschedule',
            name='parsing',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_schedules', to='home.parsing'),
        ),
    ]
