# Generated by Django 5.0.9 on 2024-11-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_alter_historicaloneoffschedule_parsing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloneoffschedule',
            name='duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='historicalregularschedule',
            name='duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='oneoffschedule',
            name='duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='regularschedule',
            name='duration_in_minutes',
        ),
    ]
