# Generated by Django 5.2.9 on 2026-01-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0004_alter_historicalimage_website_alter_image_website'),
        ('fetching', '0009_alter_historicaloclochermatchingmoderation_diocese_and_more'),
        ('front', '0003_alter_historicalreportmoderation_diocese_and_more'),
        ('home', '0123_remove_church_parish_remove_churchmoderation_church_and_more'),
        ('scheduling', '0017_alter_historicalparsingmoderation_diocese_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.DeleteModel(
            name='Church',
        ),
        migrations.DeleteModel(
            name='ChurchModeration',
        ),
        migrations.DeleteModel(
            name='ChurchTrouverUneMesse',
        ),
        migrations.DeleteModel(
            name='ChurchTrouverUneMesseLLMName',
        ),
        migrations.DeleteModel(
            name='Diocese',
        ),
        migrations.DeleteModel(
            name='HistoricalChurch',
        ),
        migrations.DeleteModel(
            name='HistoricalChurchModeration',
        ),
        migrations.DeleteModel(
            name='HistoricalDiocese',
        ),
        migrations.DeleteModel(
            name='HistoricalParish',
        ),
        migrations.DeleteModel(
            name='HistoricalParishModeration',
        ),
        migrations.DeleteModel(
            name='HistoricalWebsite',
        ),
        migrations.DeleteModel(
            name='HistoricalWebsiteModeration',
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
        migrations.DeleteModel(
            name='ParishModeration',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='WebsiteModeration',
        ),
    ])]
