# Generated by Django 5.0.9 on 2024-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_remove_historicaloneoffschedule_duration_in_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='source',
            field=models.CharField(choices=[('human', 'HUMAN'), ('ml', 'ML')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.CharField(choices=[('human', 'HUMAN'), ('ml', 'ML')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=4),
        ),
    ]
