# Generated by Django 5.0.9 on 2024-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_alter_historicalsentence_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='test_size',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='test_size',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='weekday_iso8601',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='weekday_iso8601',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
