# Generated by Django 5.0.9 on 2024-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_classifier_test_size_historicalclassifier_test_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloneoffschedule',
            name='start_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalregularschedule',
            name='start_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='oneoffschedule',
            name='start_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='regularschedule',
            name='start_time_iso8601',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
