# Generated by Django 5.0.9 on 2024-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0127_alter_historicaloneoffschedule_start_time_iso8601_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsite',
            name='unreliability_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='unreliability_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
