# Generated by Django 5.0.9 on 2024-11-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_historicalwebsite_unreliability_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsite',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('javascript_required', 'Javascript Required'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200')], null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='unreliability_reason',
            field=models.CharField(blank=True, choices=[('schedule_in_image', 'Schedule In Image'), ('javascript_required', 'Javascript Required'), ('not_responding_at_all', 'Not Responding At All'), ('not_responding_in_time', 'Not Responding In Time'), ('not_responding_200', 'Not Responding 200')], null=True),
        ),
    ]
