# Generated by Django 5.0.9 on 2024-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_remove_scraping_pruning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='prunings',
            field=models.ManyToManyField(related_name='scrapings', to='home.pruning'),
        ),
    ]
