# Generated by Django 5.0.9 on 2024-11-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0132_alter_scraping_prunings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsentence',
            old_name='pruning',
            new_name='updated_on_pruning',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='pruning',
            new_name='updated_on_pruning',
        ),
    ]
