# Generated by Django 5.0.9 on 2024-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_rename_pruning_historicalsentence_updated_on_pruning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='other_action',
            field=models.CharField(choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5),
        ),
    ]
