# Generated by Django 5.0.9 on 2024-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_alter_historicalsentence_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='prunings',
            field=models.ManyToManyField(related_name='sentences', to='home.pruning'),
        ),
    ]
