# Generated by Django 5.0.9 on 2024-11-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_sentence_prunings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpruning',
            name='pruned_html',
        ),
        migrations.RemoveField(
            model_name='historicalpruningmoderation',
            name='pruned_html',
        ),
        migrations.RemoveField(
            model_name='pruning',
            name='pruned_html',
        ),
        migrations.RemoveField(
            model_name='pruningmoderation',
            name='pruned_html',
        ),
    ]
