##
# Clone and pull the repo
##

# https://www.edureka.co/community/41267/install-git-using-ansible
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone or pull the latest code
  git: repo={{ code_repository_url }}
        dest={{ app_dir }}