##
# Set up and configure postgres
# Inspired by :
# - https://stormatics.tech/blogs/install-postgresql-using-ansible-on-remote-servers
# - https://gist.github.com/kharandziuk/d11aab8b1560d408032911140a0b103a
##
- name: add postgres repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Download PostgreSQL key and add it to system keyring
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: install pg
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
  - "python-psycopg2"
  - "postgresql-{{ pg_version }}"
  - "postgresql-contrib-{{ pg_version }}"
  - "postgresql-{{ pg_version }}-postgis-2.2"

- name: Run initdb command
  raw: postgresql-setup initdb
  become: yes

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user: db={{ app_name }}
                                name={{ db_user }}
                                password={{ db_password }}
                                priv=ALL
                                role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres

- name: install postgis extension
  postgresql_ext:
    name: postgis
    db: "{{ app_name }}"
  become: true
  become_user: postgres