##
# Set up and configure postgres
# Inspired by :
# - https://stormatics.tech/blogs/install-postgresql-using-ansible-on-remote-servers
# - https://gist.github.com/kharandziuk/d11aab8b1560d408032911140a0b103a


- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: install pg
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - "postgresql"
  - "postgresql-contrib"
  - "postgresql-postgis"
  become: true

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: true

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres

- name: Configure a new postgresql user
  postgresql_user: db={{ app_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   role_attr_flags=NOSUPERUSER
  become_user: postgres
  notify:
    - restart postgres

- name: install postgis extension
  postgresql_ext:
    name: postgis
    db: "{{ app_name }}"
  become: true
  become_user: postgres