##
# Run db migrations and get all static files
##
- name: Migrate database
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py migrate"

- name: Make www-data as owner of static files directory
  file:
    dest: "{{ static_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
    mode: "777"
  become: true

- name: Add user to www-data group
  ansible.builtin.user:
    name: "{{ deployer_user }}"
    append: true
    groups: www-data
  become: true

- name: Get all static files
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py collectstatic --noinput"

- name: Add cron for daily backup
  cron:
    name: daily_backup
    special_time: daily
    job: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py dbbackup --compress"

- name: Add cron for weekly backup
  cron:
    name: weekly_backup
    special_time: weekly
    job: ". {{ app_dir }}/.env; DBBACKUP_BUCKET=confessio-dbbackup-weekly {{ venv_python }} {{ app_dir }}/manage.py dbbackup --compress"

