ALL_FRENCH_DEPARTMENTS = {
    "01": "01, Ain, Auvergne-Rhône-Alpes",
    "02": "02, Aisne, Hauts-de-France",
    "03": "03, Allier, Auvergne-Rhône-Alpes",
    "04": "04, Alpes-de-Haute-Provence, Provence-Alpes-Côte d'Azur",
    "05": "05, Hautes-Alpes, Provence-Alpes-Côte d'Azur",
    "06": "06, Alpes-Maritimes, Provence-Alpes-Côte d'Azur",
    "07": "07, Ardèche, Auvergne-Rhône-Alpes",
    "08": "08, Ardennes, Grand Est",
    "09": "09, Ariège, Occitanie",
    "10": "10, Aube, Grand Est",
    "11": "11, Aude, Occitanie",
    "12": "12, Aveyron, Occitanie",
    "13": "13, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur",
    "14": "14, Calvados, Normandie",
    "15": "15, Cantal, Auvergne-Rhône-Alpes",
    "16": "16, Charente, Nouvelle-Aquitaine",
    "17": "17, Charente-Maritime, Nouvelle-Aquitaine",
    "18": "18, Cher, Centre-Val de Loire",
    "19": "19, Corrèze, Nouvelle-Aquitaine",
    "21": "21, Côte-d'Or, Bourgogne-Franche-Comté",
    "22": "22, Côtes-d'Armor, Bretagne",
    "23": "23, Creuse, Nouvelle-Aquitaine",
    "24": "24, Dordogne, Nouvelle-Aquitaine",
    "25": "25, Doubs, Bourgogne-Franche-Comté",
    "26": "26, Drôme, Auvergne-Rhône-Alpes",
    "27": "27, Eure, Normandie",
    "28": "28, Eure-et-Loir, Centre-Val de Loire",
    "29": "29, Finistère, Bretagne",
    "2A": "2A, Corse-du-Sud, Corse",
    "2B": "2B, Haute-Corse, Corse",
    "30": "30, Gard, Occitanie",
    "31": "31, Haute-Garonne, Occitanie",
    "32": "32, Gers, Occitanie",
    "33": "33, Gironde, Nouvelle-Aquitaine",
    "34": "34, Hérault, Occitanie",
    "35": "35, Ille-et-Vilaine, Bretagne",
    "36": "36, Indre, Centre-Val de Loire",
    "37": "37, Indre-et-Loire, Centre-Val de Loire",
    "38": "38, Isère, Auvergne-Rhône-Alpes",
    "39": "39, Jura, Bourgogne-Franche-Comté",
    "40": "40, Landes, Nouvelle-Aquitaine",
    "41": "41, Loir-et-Cher, Centre-Val de Loire",
    "42": "42, Loire, Auvergne-Rhône-Alpes",
    "43": "43, Haute-Loire, Auvergne-Rhône-Alpes",
    "44": "44, Loire-Atlantique, Pays de la Loire",
    "45": "45, Loiret, Centre-Val de Loire",
    "46": "46, Lot, Occitanie",
    "47": "47, Lot-et-Garonne, Nouvelle-Aquitaine",
    "48": "48, Lozère, Occitanie",
    "49": "49, Maine-et-Loire, Pays de la Loire",
    "50": "50, Manche, Normandie",
    "51": "51, Marne, Grand Est",
    "52": "52, Haute-Marne, Grand Est",
    "53": "53, Mayenne, Pays de la Loire",
    "54": "54, Meurthe-et-Moselle, Grand Est",
    "55": "55, Meuse, Grand Est",
    "56": "56, Morbihan, Bretagne",
    "57": "57, Moselle, Grand Est",
    "58": "58, Nièvre, Bourgogne-Franche-Comté",
    "59": "59, Nord, Hauts-de-France",
    "60": "60, Oise, Hauts-de-France",
    "61": "61, Orne, Normandie",
    "62": "62, Pas-de-Calais, Hauts-de-France",
    "63": "63, Puy-de-Dôme, Auvergne-Rhône-Alpes",
    "64": "64, Pyrénées-Atlantiques, Nouvelle-Aquitaine",
    "65": "65, Hautes-Pyrénées, Occitanie",
    "66": "66, Pyrénées-Orientales, Occitanie",
    "67": "67, Bas-Rhin, Grand Est",
    "68": "68, Haut-Rhin, Grand Est",
    "69": "69, Rhône, Auvergne-Rhône-Alpes",
    "70": "70, Haute-Saône, Bourgogne-Franche-Comté",
    "71": "71, Saône-et-Loire, Bourgogne-Franche-Comté",
    "72": "72, Sarthe, Pays de la Loire",
    "73": "73, Savoie, Auvergne-Rhône-Alpes",
    "74": "74, Haute-Savoie, Auvergne-Rhône-Alpes",
    "75": "75, Paris, Île-de-France",
    "76": "76, Seine-Maritime, Normandie",
    "77": "77, Seine-et-Marne, Île-de-France",
    "78": "78, Yvelines, Île-de-France",
    "79": "79, Deux-Sèvres, Nouvelle-Aquitaine",
    "80": "80, Somme, Hauts-de-France",
    "81": "81, Tarn, Occitanie",
    "82": "82, Tarn-et-Garonne, Occitanie",
    "83": "83, Var, Provence-Alpes-Côte d'Azur",
    "84": "84, Vaucluse, Provence-Alpes-Côte d'Azur",
    "85": "85, Vendée, Pays de la Loire",
    "86": "86, Vienne, Nouvelle-Aquitaine",
    "87": "87, Haute-Vienne, Nouvelle-Aquitaine",
    "88": "88, Vosges, Grand Est",
    "89": "89, Yonne, Bourgogne-Franche-Comté",
    "90": "90, Territoire de Belfort, Bourgogne-Franche-Comté",
    "91": "91, Essonne, Île-de-France",
    "92": "92, Hauts-de-Seine, Île-de-France",
    "93": "93, Seine-Saint-Denis, Île-de-France",
    "94": "94, Val-de-Marne, Île-de-France",
    "95": "95, Val-d'Oise, Île-de-France",
    "971": "971, Guadeloupe, Guadeloupe",
    "972": "972, Martinique, Martinique",
    "973": "973, Guyane, Guyane",
    "974": "974, La Réunion, La Réunion",
    "976": "976, Mayotte, Mayotte",
}


def get_department(zipcode: str):
    if zipcode.startswith('97'):
        return zipcode[:3]
    else:
        return zipcode[:2]


def get_departments(zipcodes: set[str]):
    return set(get_department(zipcode) for zipcode in zipcodes)


def get_department_context(department: str):
    return ALL_FRENCH_DEPARTMENTS[department]


def get_departments_context(zipcodes: set[str]):
    departments = get_departments(zipcodes)
    contexts = list(map(get_department_context, departments))

    return ' '.join(contexts)
