# Generated by Django 5.2.8 on 2025-12-05 18:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0096_alter_historicalwebsitemoderation_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOClocherMatching',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('church_json', models.JSONField(editable=False)),
                ('church_json_hash', models.CharField(editable=False, max_length=32)),
                ('location_json', models.JSONField(editable=False)),
                ('location_json_hash', models.CharField(editable=False, max_length=32)),
                ('llm_json', models.JSONField(blank=True, null=True)),
                ('llm_provider', models.CharField(choices=[('openai', 'OPENAI')])),
                ('llm_model', models.CharField(max_length=100)),
                ('prompt_template_hash', models.CharField(max_length=32)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_json', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical o clocher matching',
                'verbose_name_plural': 'historical o clocher matchings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OClocherMatching',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church_json', models.JSONField(editable=False)),
                ('church_json_hash', models.CharField(editable=False, max_length=32)),
                ('location_json', models.JSONField(editable=False)),
                ('location_json_hash', models.CharField(editable=False, max_length=32)),
                ('llm_json', models.JSONField(blank=True, null=True)),
                ('llm_provider', models.CharField(choices=[('openai', 'OPENAI')])),
                ('llm_model', models.CharField(max_length=100)),
                ('prompt_template_hash', models.CharField(max_length=32)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('church_json_hash', 'location_json_hash')},
            },
        ),
        migrations.CreateModel(
            name='OClocherOrganization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.CharField(max_length=32, unique=True)),
                ('matching', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='fetching.oclochermatching')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization', to='home.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OClocherLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fetching.oclocherorganization')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOClocherSchedule',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('schedule_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('selection', models.CharField(max_length=16)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('recurrence_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fetching.oclocherlocation')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fetching.oclocherorganization')),
            ],
            options={
                'verbose_name': 'historical o clocher schedule',
                'verbose_name_plural': 'historical o clocher schedules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OClocherSchedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('selection', models.CharField(max_length=16)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('recurrence_id', models.UUIDField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fetching.oclocherlocation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fetching.oclocherorganization')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
