# Generated by Django 5.2.8 on 2025-12-12 17:31

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0001_initial'),
        ('home', '0098_alter_historicalwebsitemoderation_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloclochermatching',
            old_name='church_json',
            new_name='church_desc_by_id',
        ),
        migrations.RenameField(
            model_name='historicaloclochermatching',
            old_name='human_json',
            new_name='human_matrix',
        ),
        migrations.RenameField(
            model_name='historicaloclochermatching',
            old_name='llm_json',
            new_name='llm_matrix',
        ),
        migrations.RenameField(
            model_name='historicaloclochermatching',
            old_name='location_json',
            new_name='location_desc_by_id',
        ),
        migrations.RenameField(
            model_name='oclochermatching',
            old_name='church_json',
            new_name='church_desc_by_id',
        ),
        migrations.RenameField(
            model_name='oclochermatching',
            old_name='human_json',
            new_name='human_matrix',
        ),
        migrations.RenameField(
            model_name='oclochermatching',
            old_name='llm_json',
            new_name='llm_matrix',
        ),
        migrations.RenameField(
            model_name='oclochermatching',
            old_name='location_json',
            new_name='location_desc_by_id',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatching',
            name='church_json_hash',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatching',
            name='location_json_hash',
        ),
        migrations.AlterUniqueTogether(
            name='oclochermatching',
            unique_together={('church_desc_by_id', 'location_desc_by_id')},
        ),
        migrations.CreateModel(
            name='HistoricalOClocherMatchingModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('new_matching', 'New Matching'), ('matching_differ', 'Matching'), ('llm_error', 'Llm Error')], max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diocese', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oclocher_matching', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fetching.oclochermatching')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical o clocher matching moderation',
                'verbose_name_plural': 'historical o clocher matching moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOClocherOrganizationModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('mutliple_widgets', 'Multiple Widgets'), ('shared_widget', 'Shared Widget')], max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diocese', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.diocese')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_as_bug_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oclocher_organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fetching.oclocherorganization')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
            ],
            options={
                'verbose_name': 'historical o clocher organization moderation',
                'verbose_name_plural': 'historical o clocher organization moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='oclochermatching',
            name='church_json_hash',
        ),
        migrations.RemoveField(
            model_name='oclochermatching',
            name='location_json_hash',
        ),
        migrations.CreateModel(
            name='OClocherMatchingModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('new_matching', 'New Matching'), ('matching_differ', 'Matching'), ('llm_error', 'Llm Error')], max_length=32)),
                ('diocese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_matching_moderations', to='home.diocese')),
                ('marked_as_bug_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oclocher_matching_marked_as_bug_by', to=settings.AUTH_USER_MODEL)),
                ('oclocher_matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='fetching.oclochermatching')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oclocher_matching_validated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('oclocher_matching', 'category')},
            },
        ),
        migrations.CreateModel(
            name='OClocherOrganizationModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('marked_as_bug_at', models.DateTimeField(null=True)),
                ('bug_description', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(choices=[('mutliple_widgets', 'Multiple Widgets'), ('shared_widget', 'Shared Widget')], max_length=32)),
                ('diocese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization_moderations', to='home.diocese')),
                ('marked_as_bug_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oclocher_organization_marked_as_bug_by', to=settings.AUTH_USER_MODEL)),
                ('oclocher_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations', to='fetching.oclocherorganization')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oclocher_organization_validated_by', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization_moderations', to='home.website')),
            ],
            options={
                'unique_together': {('website', 'category')},
            },
        ),
    ]
