# Generated by Django 5.2.9 on 2025-12-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0002_rename_church_json_historicaloclochermatching_church_desc_by_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oclocherorganization',
            options={'get_latest_by': ['updated_at']},
        ),
    ]
