# Generated by Django 5.2.9 on 2026-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0004_remove_oclocherorganization_matching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloclocherlocation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='oclocherlocation',
            name='content',
        ),
    ]
