# Generated by Django 5.2.9 on 2026-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0006_alter_historicaloclocherschedule_recurrence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloclocherschedule',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oclocherschedule',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
