# Generated by Django 5.2.9 on 2026-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0007_alter_historicaloclocherschedule_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oclochermatching',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicaloclochermatching',
            name='church_desc_by_id_hash',
            field=models.CharField(default=None, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaloclochermatching',
            name='location_desc_by_id_hash',
            field=models.CharField(default=None, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oclochermatching',
            name='church_desc_by_id_hash',
            field=models.CharField(default=None, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oclochermatching',
            name='location_desc_by_id_hash',
            field=models.CharField(default=None, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='oclochermatching',
            unique_together={('church_desc_by_id_hash', 'location_desc_by_id_hash')},
        ),
    ]
