# Generated by Django 5.2.9 on 2026-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0008_alter_oclochermatching_unique_together_and_more'),
        ('registry', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='historicaloclochermatchingmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='historicaloclocherorganizationmoderation',
            name='diocese',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='historicaloclocherorganizationmoderation',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_matching_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='oclocherorganization',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='oclocherorganizationmoderation',
            name='diocese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='oclocherorganizationmoderation',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization_moderations', to='registry.website'),
        ),
    ])]
