# Generated by Django 5.2.11 on 2026-02-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0009_alter_historicaloclochermatchingmoderation_diocese_and_more'),
        ('registry', '0005_remove_historicalwebsitemoderation_conflict_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oclocherorganization',
            name='hypertext',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oclocherorganization',
            name='hypertext_redirected',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oclocherorganization',
            name='redirected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloclocherorganizationmoderation',
            name='category',
            field=models.CharField(choices=[('mutliple_widgets', 'Multiple Widgets'), ('shared_widget', 'Shared Widget'), ('not_found', 'Not Found')], max_length=32),
        ),
        migrations.AlterField(
            model_name='oclocherorganization',
            name='website',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oclocher_organization', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='oclocherorganizationmoderation',
            name='category',
            field=models.CharField(choices=[('mutliple_widgets', 'Multiple Widgets'), ('shared_widget', 'Shared Widget'), ('not_found', 'Not Found')], max_length=32),
        ),
    ]
