# Generated by Django 5.2.11 on 2026-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0010_oclocherorganization_hypertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloclocherschedule',
            name='recurrence_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='oclocherschedule',
            name='recurrence_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
