# Generated by Django 5.2.11 on 2026-02-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0011_alter_historicaloclocherschedule_recurrence_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oclochermatchingmoderation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicaloclochermatchingmoderation',
            name='category',
            field=models.CharField(choices=[('llm_error', 'Llm Error'), ('churches_missing', 'Churches Missing'), ('ok', 'Ok')], max_length=16),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='category',
            field=models.CharField(choices=[('llm_error', 'Llm Error'), ('churches_missing', 'Churches Missing'), ('ok', 'Ok')], max_length=16),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='oclocher_matching',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='fetching.oclochermatching'),
        ),
    ]
