# Generated by Django 5.2.11 on 2026-02-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0012_alter_oclochermatchingmoderation_unique_together_and_more'),
        ('registry', '0005_remove_historicalwebsitemoderation_conflict_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloclochermatchingmoderation',
            name='oclocher_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fetching.oclocherorganization'),
        ),
        migrations.AddField(
            model_name='oclochermatchingmoderation',
            name='oclocher_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_moderations', to='fetching.oclocherorganization'),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_matching_moderations', to='registry.diocese'),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='oclocher_matching',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='fetching.oclochermatching'),
        ),
        migrations.AlterField(
            model_name='oclocherorganizationmoderation',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oclocher_organization_moderations', to='registry.diocese'),
        ),
    ]
