# Generated by Django 5.2.11 on 2026-03-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0013_historicaloclochermatchingmoderation_oclocher_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='oclocher_organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_moderation', to='fetching.oclocherorganization'),
        ),
    ]
