# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0014_alter_oclochermatchingmoderation_oclocher_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloclochermatchingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicaloclocherorganizationmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oclochermatchingmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oclocherorganizationmoderation',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
