# Generated by Django 5.2.13 on 2026-04-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0016_historicaloclochermatchingmoderation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloclochermatchingmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatchingmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatchingmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatchingmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='historicaloclochermatchingmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='historicaloclocherorganizationmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='historicaloclocherorganizationmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='historicaloclocherorganizationmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='historicaloclocherorganizationmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='historicaloclocherorganizationmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='oclochermatchingmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='oclochermatchingmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='oclochermatchingmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='oclochermatchingmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='oclochermatchingmoderation',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='oclocherorganizationmoderation',
            name='bug_description',
        ),
        migrations.RemoveField(
            model_name='oclocherorganizationmoderation',
            name='marked_as_bug_at',
        ),
        migrations.RemoveField(
            model_name='oclocherorganizationmoderation',
            name='marked_as_bug_by',
        ),
        migrations.RemoveField(
            model_name='oclocherorganizationmoderation',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='oclocherorganizationmoderation',
            name='validated_by',
        ),
    ]
