# Generated by Django 5.2.13 on 2026-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetching', '0017_remove_historicaloclochermatchingmoderation_bug_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloclochermatchingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='historicaloclocherorganizationmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='oclochermatchingmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
        migrations.AlterField(
            model_name='oclocherorganizationmoderation',
            name='status',
            field=models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12),
        ),
    ]
