# Generated by Django 5.2.9 on 2026-01-19 19:54

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='HistoricalImage',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, null=True)),
                ('llm_html', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_html', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.website')),
            ],
            options={
                'verbose_name': 'historical image',
                'verbose_name_plural': 'historical images',
                'db_table': 'home_historicalimage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        )]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True, null=True)),
                ('llm_html', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_html', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('prunings', models.ManyToManyField(related_name='images', to='home.pruning')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.website')),
            ],
            options={
                'db_table': 'home_image',
            },
        )]),
    ]
