# Generated by Django 5.2.9 on 2026-01-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': ['updated_at']},
        ),
        migrations.AlterModelTable(
            name='historicalimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
