# Generated by Django 5.2.9 on 2026-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0002_alter_image_options_alter_historicalimage_table_and_more'),
        ('scheduling', '0014_classifier_pruning_historicalclassifier_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='image',
            name='prunings',
            field=models.ManyToManyField(related_name='images', to='scheduling.pruning'),
        ),
    ])]
