# Generated by Django 5.2.9 on 2026-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0003_alter_image_prunings'),
        ('registry', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='historicalimage',
            name='website',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.website'),
        ),
        migrations.AlterField(
            model_name='image',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='registry.website'),
        ),
    ])]
