# Generated by Django 5.2.16 on 2026-09-07 12:24

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0007_pdfrecognition_nb_pages_pdfrecognition_pdf_size'),
        ('registry', '0020_immutable_unaccent_search_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImageModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_image', 'New Image')], max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diocese', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attaching.image')),
            ],
            options={
                'verbose_name': 'historical image moderation',
                'verbose_name_plural': 'historical image moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImageModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_image', 'New Image')], max_length=16)),
                ('diocese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_moderations', to='registry.diocese')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='attaching.image')),
            ],
            options={
                'unique_together': {('image', 'category')},
            },
        ),
    ]
